export interface HoroscopeRule {
  id: number;
  condition: {
    planet?: string;
    house?: number;
    houses?: number[];
    planet2?: string;
    house2?: number;
    type: "planet_in_house" | "planet_strong" | "planet_weak" | "lagna" | "conjunction" | "aspect";
  };
  category: string;
  malayalam_text: string;
  english_text: string;
  severity: "positive" | "neutral" | "negative";
}

export const HOROSCOPE_RULES: HoroscopeRule[] = [
  // ─── LAGNA RULES (12) ───
  { id: 1, condition: { type: "lagna", house: 1 }, category: "ലഗ്നം", malayalam_text: "നിങ്ങളുടെ ലഗ്നം മേടം ആണ്. ധൈര്യവും നേതൃത്വ ശേഷിയും നിങ്ങളുടെ സ്വഭാവ സവിശേഷതകളാണ്.", english_text: "Your ascendant is Aries. Courage and leadership are your key traits.", severity: "positive" },
  { id: 2, condition: { type: "lagna", house: 2 }, category: "ലഗ്നം", malayalam_text: "നിങ്ങളുടെ ലഗ്നം ഇടവം ആണ്. സ്ഥിരതയും ക്ഷമയും നിങ്ങളുടെ ശക്തിയാണ്.", english_text: "Your ascendant is Taurus. Stability and patience are your strengths.", severity: "positive" },
  { id: 3, condition: { type: "lagna", house: 3 }, category: "ലഗ്നം", malayalam_text: "നിങ്ങളുടെ ലഗ്നം മിഥുനം ആണ്. ബുദ്ധിശക്തിയും ആശയവിനിമയ ശേഷിയും മികച്ചതാണ്.", english_text: "Your ascendant is Gemini. Intelligence and communication skills are excellent.", severity: "positive" },
  { id: 4, condition: { type: "lagna", house: 4 }, category: "ലഗ്നം", malayalam_text: "നിങ്ങളുടെ ലഗ്നം കർക്കടകം ആണ്. വൈകാരിക സംവേദനക്ഷമതയും കുടുംബ സ്നേഹവും പ്രധാനമാണ്.", english_text: "Your ascendant is Cancer. Emotional sensitivity and family love are important.", severity: "positive" },
  { id: 5, condition: { type: "lagna", house: 5 }, category: "ലഗ്നം", malayalam_text: "നിങ്ങളുടെ ലഗ്നം ചിങ്ങം ആണ്. ആത്മവിശ്വാസവും പ്രതാപവും നിങ്ങളുടെ മുഖമുദ്രയാണ്.", english_text: "Your ascendant is Leo. Confidence and dignity are your hallmarks.", severity: "positive" },
  { id: 6, condition: { type: "lagna", house: 6 }, category: "ലഗ്നം", malayalam_text: "നിങ്ങളുടെ ലഗ്നം കന്നി ആണ്. വിശദാംശങ്ങളിലേക്കുള്ള ശ്രദ്ധയും വിശ്ലേഷണ ശേഷിയും മികച്ചതാണ്.", english_text: "Your ascendant is Virgo. Attention to detail and analytical ability are excellent.", severity: "positive" },
  { id: 7, condition: { type: "lagna", house: 7 }, category: "ലഗ്നം", malayalam_text: "നിങ്ങളുടെ ലഗ്നം തുലാം ആണ്. സന്തുലിതത്വവും നീതിബോധവും നിങ്ങളുടെ സ്വഭാവ സവിശേഷതയാണ്.", english_text: "Your ascendant is Libra. Balance and sense of justice are your traits.", severity: "positive" },
  { id: 8, condition: { type: "lagna", house: 8 }, category: "ലഗ്നം", malayalam_text: "നിങ്ങളുടെ ലഗ്നം വൃശ്ചികം ആണ്. തീവ്രതയും ദൃഢനിശ്ചയവും നിങ്ങളുടെ ശക്തിയാണ്.", english_text: "Your ascendant is Scorpio. Intensity and determination are your strengths.", severity: "positive" },
  { id: 9, condition: { type: "lagna", house: 9 }, category: "ലഗ്നം", malayalam_text: "നിങ്ങളുടെ ലഗ്നം ധനു ആണ്. ശുഭാപ്തിവിശ്വാസവും ജ്ഞാനതൃഷ്ണയും പ്രധാനമാണ്.", english_text: "Your ascendant is Sagittarius. Optimism and thirst for knowledge are important.", severity: "positive" },
  { id: 10, condition: { type: "lagna", house: 10 }, category: "ലഗ്നം", malayalam_text: "നിങ്ങളുടെ ലഗ്നം മകരം ആണ്. അച്ചടക്കവും ഉത്തരവാദിത്തബോധവും നിങ്ങളെ വ്യത്യസ്തനാക്കുന്നു.", english_text: "Your ascendant is Capricorn. Discipline and responsibility set you apart.", severity: "positive" },
  { id: 11, condition: { type: "lagna", house: 11 }, category: "ലഗ്നം", malayalam_text: "നിങ്ങളുടെ ലഗ്നം കുംഭം ആണ്. നവീനതയും സ്വതന്ത്ര ചിന്തയും നിങ്ങളുടെ സവിശേഷതയാണ്.", english_text: "Your ascendant is Aquarius. Innovation and independent thinking are your specialties.", severity: "positive" },
  { id: 12, condition: { type: "lagna", house: 12 }, category: "ലഗ്നം", malayalam_text: "നിങ്ങളുടെ ലഗ്നം മീനം ആണ്. അന്തർദൃഷ്ടിയും ആത്മീയതയും നിങ്ങളെ നയിക്കുന്നു.", english_text: "Your ascendant is Pisces. Intuition and spirituality guide you.", severity: "positive" },

  // ─── SUN RULES (9) ───
  { id: 13, condition: { type: "planet_in_house", planet: "sun", house: 1 }, category: "വ്യക്തിത്വം", malayalam_text: "സൂര്യൻ ലഗ്നത്തിൽ ഉള്ളതിനാൽ നിങ്ങൾ ആത്മവിശ്വാസിയും നേതൃത്വ ഗുണമുള്ളയാളുമാണ്.", english_text: "Sun in the 1st house makes you confident and a natural leader.", severity: "positive" },
  { id: 14, condition: { type: "planet_in_house", planet: "sun", house: 4 }, category: "കുടുംബം", malayalam_text: "സൂര്യൻ 4-ാം ഭാവത്തിൽ ഉള്ളതിനാൽ കുടുംബ ജീവിതത്തിൽ പ്രതിബന്ധങ്ങൾ ഉണ്ടാകാം.", english_text: "Sun in the 4th house may create obstacles in family life.", severity: "negative" },
  { id: 15, condition: { type: "planet_in_house", planet: "sun", house: 7 }, category: "വിവാഹം", malayalam_text: "സൂര്യൻ 7-ാം ഭാവത്തിൽ ഉള്ളതിനാൽ വിവാഹ ജീവിതത്തിൽ അധികാര പ്രശ്നങ്ങൾ ഉണ്ടാകാം.", english_text: "Sun in the 7th house may cause power struggles in marriage.", severity: "negative" },
  { id: 16, condition: { type: "planet_in_house", planet: "sun", house: 10 }, category: "തൊഴിൽ", malayalam_text: "സൂര്യൻ 10-ാം ഭാവത്തിൽ ഉള്ളതിനാൽ ഉയർന്ന സ്ഥാനമാനങ്ങൾ ലഭിക്കും.", english_text: "Sun in the 10th house brings high positions and authority.", severity: "positive" },
  { id: 17, condition: { type: "planet_in_house", planet: "sun", house: 2 }, category: "ധനം", malayalam_text: "സൂര്യൻ 2-ാം ഭാവത്തിൽ ഉള്ളതിനാൽ ധന ലാഭം ഉണ്ടാകും, പക്ഷേ ചെലവുകളും കൂടും.", english_text: "Sun in the 2nd house brings wealth but also increased expenses.", severity: "neutral" },
  { id: 18, condition: { type: "planet_in_house", planet: "sun", house: 5 }, category: "വിദ്യാഭ്യാസം", malayalam_text: "സൂര്യൻ 5-ാം ഭാവത്തിൽ ഉള്ളതിനാൽ ബുദ്ധിശക്തിയും സർഗ്ഗാത്മകതയും മികച്ചതാണ്.", english_text: "Sun in the 5th house gives excellent intelligence and creativity.", severity: "positive" },
  { id: 19, condition: { type: "planet_in_house", planet: "sun", house: 6 }, category: "ആരോഗ്യം", malayalam_text: "സൂര്യൻ 6-ാം ഭാവത്തിൽ ഉള്ളതിനാൽ ശത്രുക്കളെ ജയിക്കും, പക്ഷേ ആരോഗ്യ ശ്രദ്ധ വേണം.", english_text: "Sun in the 6th house helps defeat enemies but requires health attention.", severity: "neutral" },
  { id: 20, condition: { type: "planet_in_house", planet: "sun", house: 9 }, category: "ഭാഗ്യം", malayalam_text: "സൂര്യൻ 9-ാം ഭാവത്തിൽ ഉള്ളതിനാൽ ഭാഗ്യവും പിതൃസ്വത്തും ലഭിക്കും.", english_text: "Sun in the 9th house brings luck and paternal inheritance.", severity: "positive" },
  { id: 21, condition: { type: "planet_in_house", planet: "sun", house: 12 }, category: "ആത്മീയത", malayalam_text: "സൂര്യൻ 12-ാം ഭാവത്തിൽ ഉള്ളതിനാൽ ആത്മീയ ജീവിതത്തിൽ താൽപ്പര്യം ഉണ്ടാകും.", english_text: "Sun in the 12th house creates interest in spiritual life.", severity: "neutral" },

  // ─── MOON RULES (9) ───
  { id: 22, condition: { type: "planet_in_house", planet: "moon", house: 1 }, category: "മനസ്സ്", malayalam_text: "ചന്ദ്രൻ ലഗ്നത്തിൽ ഉള്ളതിനാൽ നിങ്ങൾ സംവേദനക്ഷമതയുള്ളയാളാണ്. ജനപ്രീതി ലഭിക്കും.", english_text: "Moon in the 1st house makes you sensitive. You will gain public popularity.", severity: "positive" },
  { id: 23, condition: { type: "planet_in_house", planet: "moon", house: 2 }, category: "ധനം", malayalam_text: "ചന്ദ്രൻ 2-ാം ഭാവത്തിൽ ഉള്ളതിനാൽ സാമ്പത്തിക സ്ഥിരത ലഭിക്കും.", english_text: "Moon in the 2nd house provides financial stability.", severity: "positive" },
  { id: 24, condition: { type: "planet_in_house", planet: "moon", house: 4 }, category: "കുടുംബം", malayalam_text: "ചന്ദ്രൻ 4-ാം ഭാവത്തിൽ ഉള്ളതിനാൽ മാതൃസ്നേഹവും സുഖജീവിതവും ലഭിക്കും.", english_text: "Moon in the 4th house brings maternal love and comfortable life.", severity: "positive" },
  { id: 25, condition: { type: "planet_in_house", planet: "moon", house: 5 }, category: "സന്താനം", malayalam_text: "ചന്ദ്രൻ 5-ാം ഭാവത്തിൽ ഉള്ളതിനാൽ സന്താന ഭാഗ്യം ഉണ്ടാകും.", english_text: "Moon in the 5th house brings blessings of children.", severity: "positive" },
  { id: 26, condition: { type: "planet_in_house", planet: "moon", house: 6 }, category: "ആരോഗ്യം", malayalam_text: "ചന്ദ്രൻ 6-ാം ഭാവത്തിൽ ഉള്ളതിനാൽ മാനസിക സമ്മർദ്ദം അനുഭവപ്പെടാം.", english_text: "Moon in the 6th house may cause mental stress.", severity: "negative" },
  { id: 27, condition: { type: "planet_in_house", planet: "moon", house: 7 }, category: "വിവാഹം", malayalam_text: "ചന്ദ്രൻ 7-ാം ഭാവത്തിൽ ഉള്ളതിനാൽ സുന്ദരനായ/സുന്ദരിയായ ജീവിതപങ്കാളി ലഭിക്കും.", english_text: "Moon in the 7th house brings a beautiful life partner.", severity: "positive" },
  { id: 28, condition: { type: "planet_in_house", planet: "moon", house: 8 }, category: "ആരോഗ്യം", malayalam_text: "ചന്ദ്രൻ 8-ാം ഭാവത്തിൽ ഉള്ളതിനാൽ ആരോഗ്യ പ്രശ്നങ്ങൾ ഉണ്ടാകാൻ സാധ്യതയുണ്ട്.", english_text: "Moon in the 8th house may lead to health issues.", severity: "negative" },
  { id: 29, condition: { type: "planet_in_house", planet: "moon", house: 10 }, category: "തൊഴിൽ", malayalam_text: "ചന്ദ്രൻ 10-ാം ഭാവത്തിൽ ഉള്ളതിനാൽ പൊതുജന സേവന രംഗത്ത് വിജയിക്കും.", english_text: "Moon in the 10th house brings success in public service.", severity: "positive" },
  { id: 30, condition: { type: "planet_in_house", planet: "moon", house: 12 }, category: "ആത്മീയത", malayalam_text: "ചന്ദ്രൻ 12-ാം ഭാവത്തിൽ ഉള്ളതിനാൽ വിദേശ യാത്രയ്ക്ക് സാധ്യതയുണ്ട്.", english_text: "Moon in the 12th house indicates possibility of foreign travel.", severity: "neutral" },

  // ─── MARS RULES (10) ───
  { id: 31, condition: { type: "planet_in_house", planet: "mars", house: 1 }, category: "വ്യക്തിത്വം", malayalam_text: "ചൊവ്വ ലഗ്നത്തിൽ ഉള്ളതിനാൽ നിങ്ങൾ ധൈര്യശാലിയും ഊർജ്ജസ്വലനുമാണ്.", english_text: "Mars in the 1st house makes you brave and energetic.", severity: "positive" },
  { id: 32, condition: { type: "planet_in_house", planet: "mars", house: 2 }, category: "ധനം", malayalam_text: "ചൊവ്വ 2-ാം ഭാവത്തിൽ ഉള്ളതിനാൽ വാക്കുകളിൽ കടുപ്പം ഉണ്ടാകും.", english_text: "Mars in the 2nd house may cause harshness in speech.", severity: "negative" },
  { id: 33, condition: { type: "planet_in_house", planet: "mars", house: 4 }, category: "കുടുംബം", malayalam_text: "ചൊവ്വ 4-ാം ഭാവത്തിൽ ഉള്ളതിനാൽ ഭൂമി, വാഹനം എന്നിവ ലഭിക്കും.", english_text: "Mars in the 4th house brings land and vehicles.", severity: "positive" },
  { id: 34, condition: { type: "planet_in_house", planet: "mars", house: 7 }, category: "വിവാഹം", malayalam_text: "ചൊവ്വ 7-ാം ഭാവത്തിൽ ഉള്ളതിനാൽ വിവാഹത്തിൽ വൈകിപ്പ് ഉണ്ടാകാം (ചൊവ്വാ ദോഷം).", english_text: "Mars in the 7th house may delay marriage (Manglik Dosha).", severity: "negative" },
  { id: 35, condition: { type: "planet_in_house", planet: "mars", house: 8 }, category: "ആരോഗ്യം", malayalam_text: "ചൊവ്വ 8-ാം ഭാവത്തിൽ ഉള്ളതിനാൽ അപകട സാധ്യത ഉണ്ട്. ശ്രദ്ധിക്കുക.", english_text: "Mars in the 8th house indicates accident risks. Be cautious.", severity: "negative" },
  { id: 36, condition: { type: "planet_in_house", planet: "mars", house: 10 }, category: "തൊഴിൽ", malayalam_text: "ചൊവ്വ 10-ാം ഭാവത്തിൽ ഉള്ളതിനാൽ സൈന്യം, പോലീസ്, എഞ്ചിനീയറിങ്ങ് മേഖലയിൽ വിജയിക്കും.", english_text: "Mars in the 10th house brings success in military, police, or engineering.", severity: "positive" },
  { id: 37, condition: { type: "planet_in_house", planet: "mars", house: 3 }, category: "ധൈര്യം", malayalam_text: "ചൊവ്വ 3-ാം ഭാവത്തിൽ ഉള്ളതിനാൽ സഹോദര ബന്ധം ശക്തമാണ്. ധൈര്യം കൂടും.", english_text: "Mars in the 3rd house strengthens sibling bonds and courage.", severity: "positive" },
  { id: 38, condition: { type: "planet_in_house", planet: "mars", house: 5 }, category: "സന്താനം", malayalam_text: "ചൊവ്വ 5-ാം ഭാവത്തിൽ ഉള്ളതിനാൽ സന്താന കാര്യത്തിൽ ശ്രദ്ധ വേണം.", english_text: "Mars in the 5th house requires attention in matters of children.", severity: "neutral" },
  { id: 39, condition: { type: "planet_in_house", planet: "mars", house: 6 }, category: "ആരോഗ്യം", malayalam_text: "ചൊവ്വ 6-ാം ഭാവത്തിൽ ഉള്ളതിനാൽ ശത്രുക്കളെ എളുപ്പത്തിൽ പരാജയപ്പെടുത്തും.", english_text: "Mars in the 6th house easily defeats enemies.", severity: "positive" },
  { id: 40, condition: { type: "planet_in_house", planet: "mars", house: 11 }, category: "ലാഭം", malayalam_text: "ചൊവ്വ 11-ാം ഭാവത്തിൽ ഉള്ളതിനാൽ വലിയ ലാഭം ഉണ്ടാകും.", english_text: "Mars in the 11th house brings great profits.", severity: "positive" },

  // ─── MERCURY RULES (8) ───
  { id: 41, condition: { type: "planet_in_house", planet: "mercury", house: 1 }, category: "വ്യക്തിത്വം", malayalam_text: "ബുധൻ ലഗ്നത്തിൽ ഉള്ളതിനാൽ ബുദ്ധിശക്തിയും വാക്ചാതുര്യവും ഉണ്ടാകും.", english_text: "Mercury in the 1st house gives intelligence and eloquence.", severity: "positive" },
  { id: 42, condition: { type: "planet_in_house", planet: "mercury", house: 2 }, category: "ധനം", malayalam_text: "ബുധൻ 2-ാം ഭാവത്തിൽ ഉള്ളതിനാൽ വ്യാപാരത്തിൽ ലാഭം ഉണ്ടാകും.", english_text: "Mercury in the 2nd house brings profit in business.", severity: "positive" },
  { id: 43, condition: { type: "planet_in_house", planet: "mercury", house: 4 }, category: "വിദ്യാഭ്യാസം", malayalam_text: "ബുധൻ 4-ാം ഭാവത്തിൽ ഉള്ളതിനാൽ ഉന്നത വിദ്യാഭ്യാസം ലഭിക്കും.", english_text: "Mercury in the 4th house provides higher education.", severity: "positive" },
  { id: 44, condition: { type: "planet_in_house", planet: "mercury", house: 5 }, category: "വിദ്യാഭ്യാസം", malayalam_text: "ബുധൻ 5-ാം ഭാവത്തിൽ ഉള്ളതിനാൽ ഗണിതത്തിലും ശാസ്ത്രത്തിലും മികവ് പുലർത്തും.", english_text: "Mercury in the 5th house excels in mathematics and science.", severity: "positive" },
  { id: 45, condition: { type: "planet_in_house", planet: "mercury", house: 7 }, category: "വിവാഹം", malayalam_text: "ബുധൻ 7-ാം ഭാവത്തിൽ ഉള്ളതിനാൽ ബുദ്ധിമതിയായ ജീവിതപങ്കാളി ലഭിക്കും.", english_text: "Mercury in the 7th house brings an intelligent life partner.", severity: "positive" },
  { id: 46, condition: { type: "planet_in_house", planet: "mercury", house: 10 }, category: "തൊഴിൽ", malayalam_text: "ബുധൻ 10-ാം ഭാവത്തിൽ ഉള്ളതിനാൽ ഐടി, അക്കൗണ്ടിങ്ങ്, എഴുത്ത് മേഖലയിൽ വിജയിക്കും.", english_text: "Mercury in the 10th house brings success in IT, accounting, or writing.", severity: "positive" },
  { id: 47, condition: { type: "planet_in_house", planet: "mercury", house: 8 }, category: "രഹസ്യം", malayalam_text: "ബുധൻ 8-ാം ഭാവത്തിൽ ഉള്ളതിനാൽ ഗവേഷണ മേഖലയിൽ താൽപ്പര്യം ഉണ്ടാകും.", english_text: "Mercury in the 8th house creates interest in research fields.", severity: "neutral" },
  { id: 48, condition: { type: "planet_in_house", planet: "mercury", house: 12 }, category: "ആത്മീയത", malayalam_text: "ബുധൻ 12-ാം ഭാവത്തിൽ ഉള്ളതിനാൽ വിദേശത്ത് പഠന അവസരം ഉണ്ടാകും.", english_text: "Mercury in the 12th house provides opportunities for studying abroad.", severity: "neutral" },

  // ─── JUPITER RULES (10) ───
  { id: 49, condition: { type: "planet_in_house", planet: "jupiter", house: 1 }, category: "വ്യക്തിത്വം", malayalam_text: "വ്യാഴം ലഗ്നത്തിൽ ഉള്ളതിനാൽ ജ്ഞാനവും ആരോഗ്യവും ഐശ്വര്യവും ലഭിക്കും.", english_text: "Jupiter in the 1st house gives wisdom, health, and prosperity.", severity: "positive" },
  { id: 50, condition: { type: "planet_in_house", planet: "jupiter", house: 2 }, category: "ധനം", malayalam_text: "വ്യാഴം 2-ാം ഭാവത്തിൽ ഉള്ളതിനാൽ വലിയ സമ്പത്ത് ഉണ്ടാകും.", english_text: "Jupiter in the 2nd house brings great wealth.", severity: "positive" },
  { id: 51, condition: { type: "planet_in_house", planet: "jupiter", house: 4 }, category: "കുടുംബം", malayalam_text: "വ്യാഴം 4-ാം ഭാവത്തിൽ ഉള്ളതിനാൽ വലിയ വീടും സുഖജീവിതവും ലഭിക്കും.", english_text: "Jupiter in the 4th house provides a big house and comfortable life.", severity: "positive" },
  { id: 52, condition: { type: "planet_in_house", planet: "jupiter", house: 5 }, category: "സന്താനം", malayalam_text: "വ്യാഴം 5-ാം ഭാവത്തിൽ ഉള്ളതിനാൽ ഉത്തമ സന്താന ഭാഗ്യം ലഭിക്കും.", english_text: "Jupiter in the 5th house brings excellent fortune of children.", severity: "positive" },
  { id: 53, condition: { type: "planet_in_house", planet: "jupiter", house: 7 }, category: "വിവാഹം", malayalam_text: "വ്യാഴം 7-ാം ഭാവത്തിൽ ഉള്ളതിനാൽ ഉത്തമ വിവാഹ ജീവിതം ലഭിക്കും.", english_text: "Jupiter in the 7th house gives an excellent married life.", severity: "positive" },
  { id: 54, condition: { type: "planet_in_house", planet: "jupiter", house: 9 }, category: "ഭാഗ്യം", malayalam_text: "വ്യാഴം 9-ാം ഭാവത്തിൽ ഉള്ളതിനാൽ ഭാഗ്യം, ധർമ്മം, ആത്മീയത എന്നിവ ശക്തമാണ്.", english_text: "Jupiter in the 9th house makes fortune, dharma, and spirituality strong.", severity: "positive" },
  { id: 55, condition: { type: "planet_in_house", planet: "jupiter", house: 10 }, category: "തൊഴിൽ", malayalam_text: "വ്യാഴം 10-ാം ഭാവത്തിൽ ഉള്ളതിനാൽ ഉയർന്ന സ്ഥാനങ്ങൾ ലഭിക്കും. സർക്കാർ ജോലി സാധ്യത.", english_text: "Jupiter in the 10th house brings high positions. Government job possible.", severity: "positive" },
  { id: 56, condition: { type: "planet_in_house", planet: "jupiter", house: 11 }, category: "ലാഭം", malayalam_text: "വ്യാഴം 11-ാം ഭാവത്തിൽ ഉള്ളതിനാൽ അപ്രതീക്ഷിത ധനലാഭം ഉണ്ടാകും.", english_text: "Jupiter in the 11th house brings unexpected financial gains.", severity: "positive" },
  { id: 57, condition: { type: "planet_in_house", planet: "jupiter", house: 6 }, category: "ആരോഗ്യം", malayalam_text: "വ്യാഴം 6-ാം ഭാവത്തിൽ ഉള്ളതിനാൽ ശത്രുക്കളിൽ നിന്ന് രക്ഷ ലഭിക്കും.", english_text: "Jupiter in the 6th house protects from enemies.", severity: "positive" },
  { id: 58, condition: { type: "planet_in_house", planet: "jupiter", house: 12 }, category: "ആത്മീയത", malayalam_text: "വ്യാഴം 12-ാം ഭാവത്തിൽ ഉള്ളതിനാൽ മോക്ഷ പ്രാപ്തി ഉണ്ടാകും. വിദേശ ജീവിതം സാധ്യത.", english_text: "Jupiter in the 12th house leads to salvation. Foreign life possible.", severity: "neutral" },

  // ─── VENUS RULES (9) ───
  { id: 59, condition: { type: "planet_in_house", planet: "venus", house: 1 }, category: "വ്യക്തിത്വം", malayalam_text: "ശുക്രൻ ലഗ്നത്തിൽ ഉള്ളതിനാൽ ആകർഷകമായ രൂപവും കലാ വാസനയും ഉണ്ടാകും.", english_text: "Venus in the 1st house gives attractive appearance and artistic talent.", severity: "positive" },
  { id: 60, condition: { type: "planet_in_house", planet: "venus", house: 2 }, category: "ധനം", malayalam_text: "ശുക്രൻ 2-ാം ഭാവത്തിൽ ഉള്ളതിനാൽ ആഡംബര ജീവിതം നയിക്കും.", english_text: "Venus in the 2nd house leads to a luxurious lifestyle.", severity: "positive" },
  { id: 61, condition: { type: "planet_in_house", planet: "venus", house: 4 }, category: "സുഖം", malayalam_text: "ശുക്രൻ 4-ാം ഭാവത്തിൽ ഉള്ളതിനാൽ വാഹനം, ഭൂമി, സുഖം എന്നിവ ലഭിക്കും.", english_text: "Venus in the 4th house provides vehicles, land, and comfort.", severity: "positive" },
  { id: 62, condition: { type: "planet_in_house", planet: "venus", house: 5 }, category: "പ്രണയം", malayalam_text: "ശുക്രൻ 5-ാം ഭാവത്തിൽ ഉള്ളതിനാൽ പ്രണയ ജീവിതം സമ്പന്നമാകും.", english_text: "Venus in the 5th house enriches love life.", severity: "positive" },
  { id: 63, condition: { type: "planet_in_house", planet: "venus", house: 7 }, category: "വിവാഹം", malayalam_text: "ശുക്രൻ 7-ാം ഭാവത്തിൽ ഉള്ളതിനാൽ ഉത്തമ ദാമ്പത്യ ജീവിതം ലഭിക്കും.", english_text: "Venus in the 7th house gives an excellent married life.", severity: "positive" },
  { id: 64, condition: { type: "planet_in_house", planet: "venus", house: 10 }, category: "തൊഴിൽ", malayalam_text: "ശുക്രൻ 10-ാം ഭാവത്തിൽ ഉള്ളതിനാൽ കല, സംഗീതം, ഫാഷൻ മേഖലയിൽ വിജയം.", english_text: "Venus in the 10th house brings success in art, music, or fashion.", severity: "positive" },
  { id: 65, condition: { type: "planet_in_house", planet: "venus", house: 6 }, category: "ആരോഗ്യം", malayalam_text: "ശുക്രൻ 6-ാം ഭാവത്തിൽ ഉള്ളതിനാൽ പ്രമേഹം പോലുള്ള രോഗങ്ങൾ ശ്രദ്ധിക്കണം.", english_text: "Venus in the 6th house requires attention to diseases like diabetes.", severity: "negative" },
  { id: 66, condition: { type: "planet_in_house", planet: "venus", house: 8 }, category: "ദീർഘായുസ്സ്", malayalam_text: "ശുക്രൻ 8-ാം ഭാവത്തിൽ ഉള്ളതിനാൽ ദീർഘായുസ്സ് ഉണ്ടാകും.", english_text: "Venus in the 8th house grants longevity.", severity: "positive" },
  { id: 67, condition: { type: "planet_in_house", planet: "venus", house: 12 }, category: "ചെലവ്", malayalam_text: "ശുക്രൻ 12-ാം ഭാവത്തിൽ ഉള്ളതിനാൽ ആഡംബര ചെലവുകൾ കൂടും.", english_text: "Venus in the 12th house increases luxury expenditures.", severity: "negative" },

  // ─── SATURN RULES (10) ───
  { id: 68, condition: { type: "planet_in_house", planet: "saturn", house: 1 }, category: "വ്യക്തിത്വം", malayalam_text: "ശനി ലഗ്നത്തിൽ ഉള്ളതിനാൽ ജീവിതത്തിന്റെ ആദ്യ കാലത്ത് കഷ്ടപ്പാടുകൾ ഉണ്ടാകും.", english_text: "Saturn in the 1st house brings hardships in early life.", severity: "negative" },
  { id: 69, condition: { type: "planet_in_house", planet: "saturn", house: 3 }, category: "ധൈര്യം", malayalam_text: "ശനി 3-ാം ഭാവത്തിൽ ഉള്ളതിനാൽ ക്രമേണ ശക്തി വർദ്ധിക്കും.", english_text: "Saturn in the 3rd house gradually increases strength.", severity: "neutral" },
  { id: 70, condition: { type: "planet_in_house", planet: "saturn", house: 4 }, category: "കുടുംബം", malayalam_text: "ശനി 4-ാം ഭാവത്തിൽ ഉള്ളതിനാൽ മാതാവുമായി പ്രശ്നങ്ങൾ ഉണ്ടാകാം.", english_text: "Saturn in the 4th house may cause issues with mother.", severity: "negative" },
  { id: 71, condition: { type: "planet_in_house", planet: "saturn", house: 7 }, category: "വിവാഹം", malayalam_text: "ശനി 7-ാം ഭാവത്തിൽ ഉള്ളതിനാൽ വിവാഹത്തിൽ വൈകിപ്പ് ഉണ്ടാകും.", english_text: "Saturn in the 7th house delays marriage.", severity: "negative" },
  { id: 72, condition: { type: "planet_in_house", planet: "saturn", house: 10 }, category: "തൊഴിൽ", malayalam_text: "ശനി 10-ാം ഭാവത്തിൽ ഉള്ളതിനാൽ തൊഴിൽ രംഗത്ത് വൈകിപ്പുകൾ ഉണ്ടാകാൻ സാധ്യതയുണ്ട്.", english_text: "Saturn in the 10th house may cause career delays.", severity: "negative" },
  { id: 73, condition: { type: "planet_in_house", planet: "saturn", house: 11 }, category: "ലാഭം", malayalam_text: "ശനി 11-ാം ഭാവത്തിൽ ഉള്ളതിനാൽ ക്രമേണ ധനലാഭം ഉണ്ടാകും.", english_text: "Saturn in the 11th house gradually brings financial gains.", severity: "positive" },
  { id: 74, condition: { type: "planet_in_house", planet: "saturn", house: 2 }, category: "ധനം", malayalam_text: "ശനി 2-ാം ഭാവത്തിൽ ഉള്ളതിനാൽ സാമ്പത്തിക കാര്യങ്ങളിൽ കരുതൽ വേണം.", english_text: "Saturn in the 2nd house requires caution in financial matters.", severity: "negative" },
  { id: 75, condition: { type: "planet_in_house", planet: "saturn", house: 5 }, category: "സന്താനം", malayalam_text: "ശനി 5-ാം ഭാവത്തിൽ ഉള്ളതിനാൽ സന്താനലബ്ധിയിൽ വൈകിപ്പ് ഉണ്ടാകാം.", english_text: "Saturn in the 5th house may delay having children.", severity: "negative" },
  { id: 76, condition: { type: "planet_in_house", planet: "saturn", house: 9 }, category: "ഭാഗ്യം", malayalam_text: "ശനി 9-ാം ഭാവത്തിൽ ഉള്ളതിനാൽ ഭാഗ്യം വൈകും, പക്ഷേ അധ്വാനം ഫലം നൽകും.", english_text: "Saturn in the 9th house delays luck, but hard work pays off.", severity: "neutral" },
  { id: 77, condition: { type: "planet_in_house", planet: "saturn", house: 12 }, category: "ചെലവ്", malayalam_text: "ശനി 12-ാം ഭാവത്തിൽ ഉള്ളതിനാൽ അനാവശ്യ ചെലവുകൾ ഉണ്ടാകും.", english_text: "Saturn in the 12th house causes unnecessary expenses.", severity: "negative" },

  // ─── RAHU RULES (8) ───
  { id: 78, condition: { type: "planet_in_house", planet: "rahu", house: 1 }, category: "വ്യക്തിത്വം", malayalam_text: "രാഹു ലഗ്നത്തിൽ ഉള്ളതിനാൽ അസാധാരണമായ വ്യക്തിത്വം ഉണ്ടാകും.", english_text: "Rahu in the 1st house creates an extraordinary personality.", severity: "neutral" },
  { id: 79, condition: { type: "planet_in_house", planet: "rahu", house: 2 }, category: "ധനം", malayalam_text: "രാഹു 2-ാം ഭാവത്തിൽ ഉള്ളതിനാൽ അപ്രതീക്ഷിത ധനലാഭം ഉണ്ടാകും.", english_text: "Rahu in the 2nd house brings unexpected wealth.", severity: "positive" },
  { id: 80, condition: { type: "planet_in_house", planet: "rahu", house: 4 }, category: "കുടുംബം", malayalam_text: "രാഹു 4-ാം ഭാവത്തിൽ ഉള്ളതിനാൽ ഗൃഹസുഖത്തിൽ തടസ്സങ്ങൾ ഉണ്ടാകാം.", english_text: "Rahu in the 4th house may create obstacles in domestic happiness.", severity: "negative" },
  { id: 81, condition: { type: "planet_in_house", planet: "rahu", house: 7 }, category: "വിവാഹം", malayalam_text: "രാഹു 7-ാം ഭാവത്തിൽ ഉള്ളതിനാൽ വിവാഹ ജീവിതത്തിൽ അസ്ഥിരത ഉണ്ടാകാം.", english_text: "Rahu in the 7th house may cause instability in married life.", severity: "negative" },
  { id: 82, condition: { type: "planet_in_house", planet: "rahu", house: 10 }, category: "തൊഴിൽ", malayalam_text: "രാഹു 10-ാം ഭാവത്തിൽ ഉള്ളതിനാൽ രാഷ്ട്രീയത്തിലോ ടെക്നോളജിയിലോ വിജയിക്കും.", english_text: "Rahu in the 10th house brings success in politics or technology.", severity: "positive" },
  { id: 83, condition: { type: "planet_in_house", planet: "rahu", house: 5 }, category: "സന്താനം", malayalam_text: "രാഹു 5-ാം ഭാവത്തിൽ ഉള്ളതിനാൽ സന്താന കാര്യത്തിൽ ശ്രദ്ധ വേണം.", english_text: "Rahu in the 5th house requires caution in matters of children.", severity: "negative" },
  { id: 84, condition: { type: "planet_in_house", planet: "rahu", house: 11 }, category: "ലാഭം", malayalam_text: "രാഹു 11-ാം ഭാവത്തിൽ ഉള്ളതിനാൽ വലിയ ധനലാഭം ഉണ്ടാകും.", english_text: "Rahu in the 11th house brings great financial gains.", severity: "positive" },
  { id: 85, condition: { type: "planet_in_house", planet: "rahu", house: 12 }, category: "ചെലവ്", malayalam_text: "രാഹു 12-ാം ഭാവത്തിൽ ഉള്ളതിനാൽ വിദേശ ജീവിതം സാധ്യത. ചെലവ് കൂടും.", english_text: "Rahu in the 12th house indicates foreign life. Expenses will increase.", severity: "neutral" },

  // ─── KETU RULES (8) ───
  { id: 86, condition: { type: "planet_in_house", planet: "ketu", house: 1 }, category: "ആത്മീയത", malayalam_text: "കേതു ലഗ്നത്തിൽ ഉള്ളതിനാൽ ആത്മീയ ജീവിതത്തിൽ താൽപ്പര്യം ഉണ്ടാകും.", english_text: "Ketu in the 1st house creates interest in spiritual life.", severity: "neutral" },
  { id: 87, condition: { type: "planet_in_house", planet: "ketu", house: 2 }, category: "ധനം", malayalam_text: "കേതു 2-ാം ഭാവത്തിൽ ഉള്ളതിനാൽ കുടുംബ സ്വത്ത് സംബന്ധിച്ച പ്രശ്നങ്ങൾ ഉണ്ടാകാം.", english_text: "Ketu in the 2nd house may cause issues related to family wealth.", severity: "negative" },
  { id: 88, condition: { type: "planet_in_house", planet: "ketu", house: 4 }, category: "കുടുംബം", malayalam_text: "കേതു 4-ാം ഭാവത്തിൽ ഉള്ളതിനാൽ മാതൃസ്ഥാനത്ത് പ്രശ്നങ്ങൾ ഉണ്ടാകാം.", english_text: "Ketu in the 4th house may cause maternal issues.", severity: "negative" },
  { id: 89, condition: { type: "planet_in_house", planet: "ketu", house: 5 }, category: "വിദ്യാഭ്യാസം", malayalam_text: "കേതു 5-ാം ഭാവത്തിൽ ഉള്ളതിനാൽ അസാധാരണ ബുദ്ധിശക്തി ഉണ്ടാകും.", english_text: "Ketu in the 5th house gives extraordinary intelligence.", severity: "positive" },
  { id: 90, condition: { type: "planet_in_house", planet: "ketu", house: 7 }, category: "വിവാഹം", malayalam_text: "കേതു 7-ാം ഭാവത്തിൽ ഉള്ളതിനാൽ വിവാഹ ജീവിതത്തിൽ പ്രശ്നങ്ങൾ ഉണ്ടാകാം.", english_text: "Ketu in the 7th house may create problems in married life.", severity: "negative" },
  { id: 91, condition: { type: "planet_in_house", planet: "ketu", house: 9 }, category: "ഭാഗ്യം", malayalam_text: "കേതു 9-ാം ഭാവത്തിൽ ഉള്ളതിനാൽ ആത്മീയ ഗുരുവിന്റെ അനുഗ്രഹം ലഭിക്കും.", english_text: "Ketu in the 9th house brings blessings from a spiritual guru.", severity: "positive" },
  { id: 92, condition: { type: "planet_in_house", planet: "ketu", house: 10 }, category: "തൊഴിൽ", malayalam_text: "കേതു 10-ാം ഭാവത്തിൽ ഉള്ളതിനാൽ തൊഴിൽ മാറ്റങ്ങൾ ഉണ്ടാകാം.", english_text: "Ketu in the 10th house may cause career changes.", severity: "neutral" },
  { id: 93, condition: { type: "planet_in_house", planet: "ketu", house: 12 }, category: "മോക്ഷം", malayalam_text: "കേതു 12-ാം ഭാവത്തിൽ ഉള്ളതിനാൽ മോക്ഷ പ്രാപ്തിക്ക് സാധ്യതയുണ്ട്.", english_text: "Ketu in the 12th house indicates possibility of spiritual liberation.", severity: "positive" },

  // ─── STRONG/WEAK PLANET RULES (12) ───
  { id: 94, condition: { type: "planet_strong", planet: "jupiter" }, category: "ഭാഗ്യം", malayalam_text: "വ്യാഴം ബലവത്താണ്. ഐശ്വര്യവും ഭാഗ്യവും നിങ്ങളെ അനുഗമിക്കും.", english_text: "Jupiter is strong. Prosperity and fortune will accompany you.", severity: "positive" },
  { id: 95, condition: { type: "planet_weak", planet: "jupiter" }, category: "ഭാഗ്യം", malayalam_text: "വ്യാഴം ദുർബലമാണ്. ഭാഗ്യ കുറവ് അനുഭവപ്പെടാം. ദോഷ പരിഹാരം ആവശ്യമാണ്.", english_text: "Jupiter is weak. Reduced fortune may be experienced. Remedies needed.", severity: "negative" },
  { id: 96, condition: { type: "planet_strong", planet: "venus" }, category: "സുഖം", malayalam_text: "ശുക്രൻ ബലവത്താണ്. സുഖജീവിതവും സൗന്ദര്യ ബോധവും മികച്ചതാണ്.", english_text: "Venus is strong. Comfortable life and aesthetic sense are excellent.", severity: "positive" },
  { id: 97, condition: { type: "planet_weak", planet: "venus" }, category: "വിവാഹം", malayalam_text: "ശുക്രൻ ദുർബലമാണ്. വിവാഹ ജീവിതത്തിൽ ശ്രദ്ധ വേണം.", english_text: "Venus is weak. Attention needed in married life.", severity: "negative" },
  { id: 98, condition: { type: "planet_strong", planet: "mars" }, category: "ധൈര്യം", malayalam_text: "ചൊവ്വ ബലവത്താണ്. ധൈര്യവും ശക്തിയും നിങ്ങളുടെ ആയുധമാണ്.", english_text: "Mars is strong. Courage and strength are your weapons.", severity: "positive" },
  { id: 99, condition: { type: "planet_weak", planet: "mars" }, category: "ആരോഗ്യം", malayalam_text: "ചൊവ്വ ദുർബലമാണ്. രക്ത സംബന്ധമായ പ്രശ്നങ്ങൾ ശ്രദ്ധിക്കണം.", english_text: "Mars is weak. Blood-related issues should be watched.", severity: "negative" },
  { id: 100, condition: { type: "planet_strong", planet: "saturn" }, category: "തൊഴിൽ", malayalam_text: "ശനി ബലവത്താണ്. അധ്വാനഫലം ലഭിക്കും. ദീർഘായുസ്സ് ഉണ്ടാകും.", english_text: "Saturn is strong. Hard work will pay off. Longevity is indicated.", severity: "positive" },
  { id: 101, condition: { type: "planet_weak", planet: "saturn" }, category: "തൊഴിൽ", malayalam_text: "ശനി ദുർബലമാണ്. തൊഴിൽ മേഖലയിൽ ബുദ്ധിമുട്ടുകൾ ഉണ്ടാകാം.", english_text: "Saturn is weak. Difficulties in career may arise.", severity: "negative" },
  { id: 102, condition: { type: "planet_strong", planet: "mercury" }, category: "വിദ്യാഭ്യാസം", malayalam_text: "ബുധൻ ബലവത്താണ്. ഉയർന്ന ബുദ്ധിശക്തിയും ആശയവിനിമയ കഴിവും ഉണ്ട്.", english_text: "Mercury is strong. High intelligence and communication skills are present.", severity: "positive" },
  { id: 103, condition: { type: "planet_weak", planet: "mercury" }, category: "വിദ്യാഭ്യാസം", malayalam_text: "ബുധൻ ദുർബലമാണ്. ഏകാഗ്രത കുറവ് അനുഭവപ്പെടാം.", english_text: "Mercury is weak. Lack of concentration may be experienced.", severity: "negative" },
  { id: 104, condition: { type: "planet_strong", planet: "sun" }, category: "ആത്മവിശ്വാസം", malayalam_text: "സൂര്യൻ ബലവത്താണ്. ആത്മവിശ്വാസവും അധികാരവും ശക്തമാണ്.", english_text: "Sun is strong. Self-confidence and authority are powerful.", severity: "positive" },
  { id: 105, condition: { type: "planet_weak", planet: "sun" }, category: "ആത്മവിശ്വാസം", malayalam_text: "സൂര്യൻ ദുർബലമാണ്. ആത്മവിശ്വാസ കുറവ് ഉണ്ടാകാം. പിതൃ ബന്ധത്തിൽ ശ്രദ്ധ.", english_text: "Sun is weak. Low self-confidence possible. Attention to paternal relations.", severity: "negative" },

  // ─── ADDITIONAL GENERAL RULES (7) ───
  { id: 106, condition: { type: "planet_in_house", planet: "sun", house: 3 }, category: "ധൈര്യം", malayalam_text: "സൂര്യൻ 3-ാം ഭാവത്തിൽ ഉള്ളതിനാൽ സഹോദരങ്ങളുമായി നല്ല ബന്ധം ഉണ്ടാകും.", english_text: "Sun in the 3rd house brings good relations with siblings.", severity: "positive" },
  { id: 107, condition: { type: "planet_in_house", planet: "sun", house: 8 }, category: "ആരോഗ്യം", malayalam_text: "സൂര്യൻ 8-ാം ഭാവത്തിൽ ഉള്ളതിനാൽ ദീർഘ രോഗങ്ങൾ ശ്രദ്ധിക്കണം.", english_text: "Sun in the 8th house requires attention to chronic diseases.", severity: "negative" },
  { id: 108, condition: { type: "planet_in_house", planet: "sun", house: 11 }, category: "ലാഭം", malayalam_text: "സൂര്യൻ 11-ാം ഭാവത്തിൽ ഉള്ളതിനാൽ ഉന്നത സുഹൃത്തുക്കളിൽ നിന്ന് സഹായം ലഭിക്കും.", english_text: "Sun in the 11th house brings help from influential friends.", severity: "positive" },
  { id: 109, condition: { type: "planet_in_house", planet: "moon", house: 3 }, category: "ആശയവിനിമയം", malayalam_text: "ചന്ദ്രൻ 3-ാം ഭാവത്തിൽ ഉള്ളതിനാൽ കലാ രംഗത്ത് വിജയിക്കും.", english_text: "Moon in the 3rd house brings success in arts.", severity: "positive" },
  { id: 110, condition: { type: "planet_in_house", planet: "moon", house: 9 }, category: "ഭാഗ്യം", malayalam_text: "ചന്ദ്രൻ 9-ാം ഭാവത്തിൽ ഉള്ളതിനാൽ ഭാഗ്യം ശക്തമാണ്. തീർത്ഥയാത്രകൾ ഉണ്ടാകും.", english_text: "Moon in the 9th house makes fortune strong. Pilgrimages will occur.", severity: "positive" },
  { id: 111, condition: { type: "planet_in_house", planet: "moon", house: 11 }, category: "ലാഭം", malayalam_text: "ചന്ദ്രൻ 11-ാം ഭാവത്തിൽ ഉള്ളതിനാൽ സാമ്പത്തിക ലാഭം ഉണ്ടാകും.", english_text: "Moon in the 11th house brings financial gains.", severity: "positive" },
  { id: 112, condition: { type: "planet_in_house", planet: "mercury", house: 3 }, category: "ആശയവിനിമയം", malayalam_text: "ബുധൻ 3-ാം ഭാവത്തിൽ ഉള്ളതിനാൽ എഴുത്ത്, മാധ്യമ രംഗത്ത് വിജയിക്കും.", english_text: "Mercury in the 3rd house brings success in writing and media.", severity: "positive" },
];
