/**
 * VLE ID helpers for the PAN Portal.
 *
 * IMPORTANT — work logic:
 *   The VLE/PSA ID is **issued by the upstream provider** (mallikacyberzone /
 *   UTI PSA portal), NOT generated by us. The retailer obtains it by:
 *     1. Submitting "PSA ID Create" once (provider returns the real ID).
 *     2. Or claiming a legacy ID they already had on the old portal.
 *
 *   The provider-issued ID is then required for "Coupon Buy" — without it
 *   the upstream API returns "Vle Data Not Exist".
 *
 *   We DO NOT auto-generate VLE IDs from the user's UID/mobile anymore
 *   (that produced fake IDs the provider's database didn't recognise).
 */

/** Strip everything except digits; keep last 10 (Indian mobile). */
function normalizeMobile(mobile: string | undefined | null): string {
  if (!mobile) return "";
  const digits = String(mobile).replace(/\D+/g, "");
  return digits.length >= 10 ? digits.slice(-10) : digits;
}

/**
 * Display-only placeholder shown in the UI before the user has registered
 * their PSA ID with the provider. Never sent to upstream APIs.
 */
export const PSA_PENDING_PLACEHOLDER = "PSA-PENDING";

/**
 * Returns the user's REAL provider-issued VLE ID if available, else a
 * placeholder string suitable only for display.
 *
 * Callers that need to send the ID to the upstream API MUST check that the
 * returned value is not equal to `PSA_PENDING_PLACEHOLDER`.
 */
export function displayVleId(
  storedPsaId: string | undefined | null,
  mobile?: string | null,
): string {
  if (storedPsaId && storedPsaId.trim()) return storedPsaId.trim();
  // Show pending + mobile suffix for staff readability.
  const m = normalizeMobile(mobile);
  return m ? `${PSA_PENDING_PLACEHOLDER}-${m}` : PSA_PENDING_PLACEHOLDER;
}

/**
 * Back-compat shim for older call sites. Prefer `displayVleId` going forward.
 * NOTE: this never invents a provider ID; it only returns a placeholder when
 * the real one isn't stored yet.
 */
export function generateVleId(
  _uid: string | undefined | null,
  mobile?: string | null,
): string {
  return displayVleId(null, mobile);
}

export function generateVleIdPrefix(_uid: string | undefined | null): string {
  return PSA_PENDING_PLACEHOLDER;
}
