/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as TrainerRouteImport } from './routes/trainer'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as RetailerRouteImport } from './routes/retailer'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as OperatorRouteImport } from './routes/operator'
import { Route as NsdlCallbackRouteImport } from './routes/nsdl-callback'
import { Route as MatrimonyRouteImport } from './routes/matrimony'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InstallRouteImport } from './routes/install'
import { Route as DistributorRouteImport } from './routes/distributor'
import { Route as BookletRouteImport } from './routes/booklet'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TrainerIndexRouteImport } from './routes/trainer.index'
import { Route as StaffIndexRouteImport } from './routes/staff.index'
import { Route as RetailerIndexRouteImport } from './routes/retailer.index'
import { Route as OperatorIndexRouteImport } from './routes/operator.index'
import { Route as MatrimonyIndexRouteImport } from './routes/matrimony.index'
import { Route as DistributorIndexRouteImport } from './routes/distributor.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as WorkerWorkerIdRouteImport } from './routes/worker.$workerId'
import { Route as TrainerWalletRouteImport } from './routes/trainer.wallet'
import { Route as TrainerTrainingsRouteImport } from './routes/trainer.trainings'
import { Route as StaffServicesRouteImport } from './routes/staff.services'
import { Route as StaffReportsRouteImport } from './routes/staff.reports'
import { Route as StaffPerformanceRouteImport } from './routes/staff.performance'
import { Route as StaffLeadsRouteImport } from './routes/staff.leads'
import { Route as StaffIppbRouteImport } from './routes/staff.ippb'
import { Route as StaffHoroscopeRequestsRouteImport } from './routes/staff.horoscope-requests'
import { Route as StaffFormsRouteImport } from './routes/staff.forms'
import { Route as StaffFormSubmissionsRouteImport } from './routes/staff.form-submissions'
import { Route as StaffDmtRouteImport } from './routes/staff.dmt'
import { Route as RetailerWorkBadgeRouteImport } from './routes/retailer.work-badge'
import { Route as RetailerWorkRouteImport } from './routes/retailer.work'
import { Route as RetailerWalletRouteImport } from './routes/retailer.wallet'
import { Route as RetailerVirtualTrainerRouteImport } from './routes/retailer.virtual-trainer'
import { Route as RetailerTransactionsRouteImport } from './routes/retailer.transactions'
import { Route as RetailerTrainingsRouteImport } from './routes/retailer.trainings'
import { Route as RetailerTrainingGuideRouteImport } from './routes/retailer.training-guide'
import { Route as RetailerStaffRouteImport } from './routes/retailer.staff'
import { Route as RetailerServicesRouteImport } from './routes/retailer.services'
import { Route as RetailerReferralsRouteImport } from './routes/retailer.referrals'
import { Route as RetailerRechargeRouteImport } from './routes/retailer.recharge'
import { Route as RetailerProfileRouteImport } from './routes/retailer.profile'
import { Route as RetailerPanPortalRouteImport } from './routes/retailer.pan-portal'
import { Route as RetailerPageToolsRouteImport } from './routes/retailer.page-tools'
import { Route as RetailerMyServicesRouteImport } from './routes/retailer.my-services'
import { Route as RetailerMoneyTransferRouteImport } from './routes/retailer.money-transfer'
import { Route as RetailerMatrimonyRouteImport } from './routes/retailer.matrimony'
import { Route as RetailerKycRouteImport } from './routes/retailer.kyc'
import { Route as RetailerJobsRouteImport } from './routes/retailer.jobs'
import { Route as RetailerIppbRouteImport } from './routes/retailer.ippb'
import { Route as RetailerHoroscopeRouteImport } from './routes/retailer.horoscope'
import { Route as RetailerFormsRouteImport } from './routes/retailer.forms'
import { Route as RetailerFinanceRouteImport } from './routes/retailer.finance'
import { Route as RetailerEiPayRouteImport } from './routes/retailer.ei-pay'
import { Route as RetailerCvBuilderRouteImport } from './routes/retailer.cv-builder'
import { Route as RetailerActivateRouteImport } from './routes/retailer.activate'
import { Route as MatrimonyProfileIdRouteImport } from './routes/matrimony.$profileId'
import { Route as DistributorWalletRouteImport } from './routes/distributor.wallet'
import { Route as DistributorEarningsRouteImport } from './routes/distributor.earnings'
import { Route as AdminWorkBadgesRouteImport } from './routes/admin.work-badges'
import { Route as AdminWalletsRouteImport } from './routes/admin.wallets'
import { Route as AdminWalletRequestsRouteImport } from './routes/admin.wallet-requests'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminTrainingsRouteImport } from './routes/admin.trainings'
import { Route as AdminTrainingSettingsRouteImport } from './routes/admin.training-settings'
import { Route as AdminTrainingReviewsRouteImport } from './routes/admin.training-reviews'
import { Route as AdminTrainingEarningsRouteImport } from './routes/admin.training-earnings'
import { Route as AdminSessionQualityRouteImport } from './routes/admin.session-quality'
import { Route as AdminServicesRouteImport } from './routes/admin.services'
import { Route as AdminServicePlansRouteImport } from './routes/admin.service-plans'
import { Route as AdminServiceButtonsRouteImport } from './routes/admin.service-buttons'
import { Route as AdminServiceActivationsConfigRouteImport } from './routes/admin.service-activations-config'
import { Route as AdminServiceActivationsRouteImport } from './routes/admin.service-activations'
import { Route as AdminReferralsRouteImport } from './routes/admin.referrals'
import { Route as AdminRechargeTransactionsRouteImport } from './routes/admin.recharge-transactions'
import { Route as AdminPsaIdsRouteImport } from './routes/admin.psa-ids'
import { Route as AdminPanSettingsRouteImport } from './routes/admin.pan-settings'
import { Route as AdminNoticesRouteImport } from './routes/admin.notices'
import { Route as AdminMatrimonyRouteImport } from './routes/admin.matrimony'
import { Route as AdminLandingCmsRouteImport } from './routes/admin.landing-cms'
import { Route as AdminKycRouteImport } from './routes/admin.kyc'
import { Route as AdminJobMarketplaceRouteImport } from './routes/admin.job-marketplace'
import { Route as AdminJobEarningsRouteImport } from './routes/admin.job-earnings'
import { Route as AdminJobDisputesRouteImport } from './routes/admin.job-disputes'
import { Route as AdminIppbSettingsRouteImport } from './routes/admin.ippb-settings'
import { Route as AdminIppbBadgesRouteImport } from './routes/admin.ippb-badges'
import { Route as AdminHoroscopeSettingsRouteImport } from './routes/admin.horoscope-settings'
import { Route as AdminFormAnalyticsRouteImport } from './routes/admin.form-analytics'
import { Route as AdminFinanceRouteImport } from './routes/admin.finance'
import { Route as AdminCscSettingsRouteImport } from './routes/admin.csc-settings'
import { Route as AdminCscMonitorRouteImport } from './routes/admin.csc-monitor'
import { Route as AdminCrmReportsRouteImport } from './routes/admin.crm-reports'
import { Route as AdminCrmLeadsRouteImport } from './routes/admin.crm-leads'
import { Route as AdminCreateUserRouteImport } from './routes/admin.create-user'
import { Route as AdminCommissionsRouteImport } from './routes/admin.commissions'
import { Route as AdminChatInboxRouteImport } from './routes/admin.chat-inbox'
import { Route as AdminCertificateReissuesRouteImport } from './routes/admin.certificate-reissues'
import { Route as RetailerJobsJobIdRouteImport } from './routes/retailer.jobs.$jobId'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainerRoute = TrainerRouteImport.update({
  id: '/trainer',
  path: '/trainer',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const RetailerRoute = RetailerRouteImport.update({
  id: '/retailer',
  path: '/retailer',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const OperatorRoute = OperatorRouteImport.update({
  id: '/operator',
  path: '/operator',
  getParentRoute: () => rootRouteImport,
} as any)
const NsdlCallbackRoute = NsdlCallbackRouteImport.update({
  id: '/nsdl-callback',
  path: '/nsdl-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const MatrimonyRoute = MatrimonyRouteImport.update({
  id: '/matrimony',
  path: '/matrimony',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InstallRoute = InstallRouteImport.update({
  id: '/install',
  path: '/install',
  getParentRoute: () => rootRouteImport,
} as any)
const DistributorRoute = DistributorRouteImport.update({
  id: '/distributor',
  path: '/distributor',
  getParentRoute: () => rootRouteImport,
} as any)
const BookletRoute = BookletRouteImport.update({
  id: '/booklet',
  path: '/booklet',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainerIndexRoute = TrainerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TrainerRoute,
} as any)
const StaffIndexRoute = StaffIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StaffRoute,
} as any)
const RetailerIndexRoute = RetailerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RetailerRoute,
} as any)
const OperatorIndexRoute = OperatorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OperatorRoute,
} as any)
const MatrimonyIndexRoute = MatrimonyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MatrimonyRoute,
} as any)
const DistributorIndexRoute = DistributorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DistributorRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const WorkerWorkerIdRoute = WorkerWorkerIdRouteImport.update({
  id: '/worker/$workerId',
  path: '/worker/$workerId',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainerWalletRoute = TrainerWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => TrainerRoute,
} as any)
const TrainerTrainingsRoute = TrainerTrainingsRouteImport.update({
  id: '/trainings',
  path: '/trainings',
  getParentRoute: () => TrainerRoute,
} as any)
const StaffServicesRoute = StaffServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => StaffRoute,
} as any)
const StaffReportsRoute = StaffReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => StaffRoute,
} as any)
const StaffPerformanceRoute = StaffPerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => StaffRoute,
} as any)
const StaffLeadsRoute = StaffLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => StaffRoute,
} as any)
const StaffIppbRoute = StaffIppbRouteImport.update({
  id: '/ippb',
  path: '/ippb',
  getParentRoute: () => StaffRoute,
} as any)
const StaffHoroscopeRequestsRoute = StaffHoroscopeRequestsRouteImport.update({
  id: '/horoscope-requests',
  path: '/horoscope-requests',
  getParentRoute: () => StaffRoute,
} as any)
const StaffFormsRoute = StaffFormsRouteImport.update({
  id: '/forms',
  path: '/forms',
  getParentRoute: () => StaffRoute,
} as any)
const StaffFormSubmissionsRoute = StaffFormSubmissionsRouteImport.update({
  id: '/form-submissions',
  path: '/form-submissions',
  getParentRoute: () => StaffRoute,
} as any)
const StaffDmtRoute = StaffDmtRouteImport.update({
  id: '/dmt',
  path: '/dmt',
  getParentRoute: () => StaffRoute,
} as any)
const RetailerWorkBadgeRoute = RetailerWorkBadgeRouteImport.update({
  id: '/work-badge',
  path: '/work-badge',
  getParentRoute: () => RetailerRoute,
} as any)
const RetailerWorkRoute = RetailerWorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => RetailerRoute,
} as any)
const RetailerWalletRoute = RetailerWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => RetailerRoute,
} as any)
const RetailerVirtualTrainerRoute = RetailerVirtualTrainerRouteImport.update({
  id: '/virtual-trainer',
  path: '/virtual-trainer',
  getParentRoute: () => RetailerRoute,
} as any)
const RetailerTransactionsRoute = RetailerTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => RetailerRoute,
} as any)
const RetailerTrainingsRoute = RetailerTrainingsRouteImport.update({
  id: '/trainings',
  path: '/trainings',
  getParentRoute: () => RetailerRoute,
} as any)
const RetailerTrainingGuideRoute = RetailerTrainingGuideRouteImport.update({
  id: '/training-guide',
  path: '/training-guide',
  getParentRoute: () => RetailerRoute,
} as any)
const RetailerStaffRoute = RetailerStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => RetailerRoute,
} as any)
const RetailerServicesRoute = RetailerServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => RetailerRoute,
} as any)
const RetailerReferralsRoute = RetailerReferralsRouteImport.update({
  id: '/referrals',
  path: '/referrals',
  getParentRoute: () => RetailerRoute,
} as any)
const RetailerRechargeRoute = RetailerRechargeRouteImport.update({
  id: '/recharge',
  path: '/recharge',
  getParentRoute: () => RetailerRoute,
} as any)
const RetailerProfileRoute = RetailerProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => RetailerRoute,
} as any)
const RetailerPanPortalRoute = RetailerPanPortalRouteImport.update({
  id: '/pan-portal',
  path: '/pan-portal',
  getParentRoute: () => RetailerRoute,
} as any)
const RetailerPageToolsRoute = RetailerPageToolsRouteImport.update({
  id: '/page-tools',
  path: '/page-tools',
  getParentRoute: () => RetailerRoute,
} as any)
const RetailerMyServicesRoute = RetailerMyServicesRouteImport.update({
  id: '/my-services',
  path: '/my-services',
  getParentRoute: () => RetailerRoute,
} as any)
const RetailerMoneyTransferRoute = RetailerMoneyTransferRouteImport.update({
  id: '/money-transfer',
  path: '/money-transfer',
  getParentRoute: () => RetailerRoute,
} as any)
const RetailerMatrimonyRoute = RetailerMatrimonyRouteImport.update({
  id: '/matrimony',
  path: '/matrimony',
  getParentRoute: () => RetailerRoute,
} as any)
const RetailerKycRoute = RetailerKycRouteImport.update({
  id: '/kyc',
  path: '/kyc',
  getParentRoute: () => RetailerRoute,
} as any)
const RetailerJobsRoute = RetailerJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => RetailerRoute,
} as any)
const RetailerIppbRoute = RetailerIppbRouteImport.update({
  id: '/ippb',
  path: '/ippb',
  getParentRoute: () => RetailerRoute,
} as any)
const RetailerHoroscopeRoute = RetailerHoroscopeRouteImport.update({
  id: '/horoscope',
  path: '/horoscope',
  getParentRoute: () => RetailerRoute,
} as any)
const RetailerFormsRoute = RetailerFormsRouteImport.update({
  id: '/forms',
  path: '/forms',
  getParentRoute: () => RetailerRoute,
} as any)
const RetailerFinanceRoute = RetailerFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => RetailerRoute,
} as any)
const RetailerEiPayRoute = RetailerEiPayRouteImport.update({
  id: '/ei-pay',
  path: '/ei-pay',
  getParentRoute: () => RetailerRoute,
} as any)
const RetailerCvBuilderRoute = RetailerCvBuilderRouteImport.update({
  id: '/cv-builder',
  path: '/cv-builder',
  getParentRoute: () => RetailerRoute,
} as any)
const RetailerActivateRoute = RetailerActivateRouteImport.update({
  id: '/activate',
  path: '/activate',
  getParentRoute: () => RetailerRoute,
} as any)
const MatrimonyProfileIdRoute = MatrimonyProfileIdRouteImport.update({
  id: '/$profileId',
  path: '/$profileId',
  getParentRoute: () => MatrimonyRoute,
} as any)
const DistributorWalletRoute = DistributorWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => DistributorRoute,
} as any)
const DistributorEarningsRoute = DistributorEarningsRouteImport.update({
  id: '/earnings',
  path: '/earnings',
  getParentRoute: () => DistributorRoute,
} as any)
const AdminWorkBadgesRoute = AdminWorkBadgesRouteImport.update({
  id: '/work-badges',
  path: '/work-badges',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWalletsRoute = AdminWalletsRouteImport.update({
  id: '/wallets',
  path: '/wallets',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWalletRequestsRoute = AdminWalletRequestsRouteImport.update({
  id: '/wallet-requests',
  path: '/wallet-requests',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTrainingsRoute = AdminTrainingsRouteImport.update({
  id: '/trainings',
  path: '/trainings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTrainingSettingsRoute = AdminTrainingSettingsRouteImport.update({
  id: '/training-settings',
  path: '/training-settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTrainingReviewsRoute = AdminTrainingReviewsRouteImport.update({
  id: '/training-reviews',
  path: '/training-reviews',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTrainingEarningsRoute = AdminTrainingEarningsRouteImport.update({
  id: '/training-earnings',
  path: '/training-earnings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSessionQualityRoute = AdminSessionQualityRouteImport.update({
  id: '/session-quality',
  path: '/session-quality',
  getParentRoute: () => AdminRoute,
} as any)
const AdminServicesRoute = AdminServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AdminRoute,
} as any)
const AdminServicePlansRoute = AdminServicePlansRouteImport.update({
  id: '/service-plans',
  path: '/service-plans',
  getParentRoute: () => AdminRoute,
} as any)
const AdminServiceButtonsRoute = AdminServiceButtonsRouteImport.update({
  id: '/service-buttons',
  path: '/service-buttons',
  getParentRoute: () => AdminRoute,
} as any)
const AdminServiceActivationsConfigRoute =
  AdminServiceActivationsConfigRouteImport.update({
    id: '/service-activations-config',
    path: '/service-activations-config',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminServiceActivationsRoute = AdminServiceActivationsRouteImport.update({
  id: '/service-activations',
  path: '/service-activations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReferralsRoute = AdminReferralsRouteImport.update({
  id: '/referrals',
  path: '/referrals',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRechargeTransactionsRoute =
  AdminRechargeTransactionsRouteImport.update({
    id: '/recharge-transactions',
    path: '/recharge-transactions',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminPsaIdsRoute = AdminPsaIdsRouteImport.update({
  id: '/psa-ids',
  path: '/psa-ids',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPanSettingsRoute = AdminPanSettingsRouteImport.update({
  id: '/pan-settings',
  path: '/pan-settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNoticesRoute = AdminNoticesRouteImport.update({
  id: '/notices',
  path: '/notices',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMatrimonyRoute = AdminMatrimonyRouteImport.update({
  id: '/matrimony',
  path: '/matrimony',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLandingCmsRoute = AdminLandingCmsRouteImport.update({
  id: '/landing-cms',
  path: '/landing-cms',
  getParentRoute: () => AdminRoute,
} as any)
const AdminKycRoute = AdminKycRouteImport.update({
  id: '/kyc',
  path: '/kyc',
  getParentRoute: () => AdminRoute,
} as any)
const AdminJobMarketplaceRoute = AdminJobMarketplaceRouteImport.update({
  id: '/job-marketplace',
  path: '/job-marketplace',
  getParentRoute: () => AdminRoute,
} as any)
const AdminJobEarningsRoute = AdminJobEarningsRouteImport.update({
  id: '/job-earnings',
  path: '/job-earnings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminJobDisputesRoute = AdminJobDisputesRouteImport.update({
  id: '/job-disputes',
  path: '/job-disputes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminIppbSettingsRoute = AdminIppbSettingsRouteImport.update({
  id: '/ippb-settings',
  path: '/ippb-settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminIppbBadgesRoute = AdminIppbBadgesRouteImport.update({
  id: '/ippb-badges',
  path: '/ippb-badges',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHoroscopeSettingsRoute = AdminHoroscopeSettingsRouteImport.update({
  id: '/horoscope-settings',
  path: '/horoscope-settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFormAnalyticsRoute = AdminFormAnalyticsRouteImport.update({
  id: '/form-analytics',
  path: '/form-analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFinanceRoute = AdminFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCscSettingsRoute = AdminCscSettingsRouteImport.update({
  id: '/csc-settings',
  path: '/csc-settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCscMonitorRoute = AdminCscMonitorRouteImport.update({
  id: '/csc-monitor',
  path: '/csc-monitor',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCrmReportsRoute = AdminCrmReportsRouteImport.update({
  id: '/crm-reports',
  path: '/crm-reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCrmLeadsRoute = AdminCrmLeadsRouteImport.update({
  id: '/crm-leads',
  path: '/crm-leads',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCreateUserRoute = AdminCreateUserRouteImport.update({
  id: '/create-user',
  path: '/create-user',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCommissionsRoute = AdminCommissionsRouteImport.update({
  id: '/commissions',
  path: '/commissions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminChatInboxRoute = AdminChatInboxRouteImport.update({
  id: '/chat-inbox',
  path: '/chat-inbox',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCertificateReissuesRoute =
  AdminCertificateReissuesRouteImport.update({
    id: '/certificate-reissues',
    path: '/certificate-reissues',
    getParentRoute: () => AdminRoute,
  } as any)
const RetailerJobsJobIdRoute = RetailerJobsJobIdRouteImport.update({
  id: '/$jobId',
  path: '/$jobId',
  getParentRoute: () => RetailerJobsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/booklet': typeof BookletRoute
  '/distributor': typeof DistributorRouteWithChildren
  '/install': typeof InstallRoute
  '/login': typeof LoginRoute
  '/matrimony': typeof MatrimonyRouteWithChildren
  '/nsdl-callback': typeof NsdlCallbackRoute
  '/operator': typeof OperatorRouteWithChildren
  '/register': typeof RegisterRoute
  '/retailer': typeof RetailerRouteWithChildren
  '/staff': typeof StaffRouteWithChildren
  '/trainer': typeof TrainerRouteWithChildren
  '/welcome': typeof WelcomeRoute
  '/admin/certificate-reissues': typeof AdminCertificateReissuesRoute
  '/admin/chat-inbox': typeof AdminChatInboxRoute
  '/admin/commissions': typeof AdminCommissionsRoute
  '/admin/create-user': typeof AdminCreateUserRoute
  '/admin/crm-leads': typeof AdminCrmLeadsRoute
  '/admin/crm-reports': typeof AdminCrmReportsRoute
  '/admin/csc-monitor': typeof AdminCscMonitorRoute
  '/admin/csc-settings': typeof AdminCscSettingsRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/form-analytics': typeof AdminFormAnalyticsRoute
  '/admin/horoscope-settings': typeof AdminHoroscopeSettingsRoute
  '/admin/ippb-badges': typeof AdminIppbBadgesRoute
  '/admin/ippb-settings': typeof AdminIppbSettingsRoute
  '/admin/job-disputes': typeof AdminJobDisputesRoute
  '/admin/job-earnings': typeof AdminJobEarningsRoute
  '/admin/job-marketplace': typeof AdminJobMarketplaceRoute
  '/admin/kyc': typeof AdminKycRoute
  '/admin/landing-cms': typeof AdminLandingCmsRoute
  '/admin/matrimony': typeof AdminMatrimonyRoute
  '/admin/notices': typeof AdminNoticesRoute
  '/admin/pan-settings': typeof AdminPanSettingsRoute
  '/admin/psa-ids': typeof AdminPsaIdsRoute
  '/admin/recharge-transactions': typeof AdminRechargeTransactionsRoute
  '/admin/referrals': typeof AdminReferralsRoute
  '/admin/service-activations': typeof AdminServiceActivationsRoute
  '/admin/service-activations-config': typeof AdminServiceActivationsConfigRoute
  '/admin/service-buttons': typeof AdminServiceButtonsRoute
  '/admin/service-plans': typeof AdminServicePlansRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/session-quality': typeof AdminSessionQualityRoute
  '/admin/training-earnings': typeof AdminTrainingEarningsRoute
  '/admin/training-reviews': typeof AdminTrainingReviewsRoute
  '/admin/training-settings': typeof AdminTrainingSettingsRoute
  '/admin/trainings': typeof AdminTrainingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/wallet-requests': typeof AdminWalletRequestsRoute
  '/admin/wallets': typeof AdminWalletsRoute
  '/admin/work-badges': typeof AdminWorkBadgesRoute
  '/distributor/earnings': typeof DistributorEarningsRoute
  '/distributor/wallet': typeof DistributorWalletRoute
  '/matrimony/$profileId': typeof MatrimonyProfileIdRoute
  '/retailer/activate': typeof RetailerActivateRoute
  '/retailer/cv-builder': typeof RetailerCvBuilderRoute
  '/retailer/ei-pay': typeof RetailerEiPayRoute
  '/retailer/finance': typeof RetailerFinanceRoute
  '/retailer/forms': typeof RetailerFormsRoute
  '/retailer/horoscope': typeof RetailerHoroscopeRoute
  '/retailer/ippb': typeof RetailerIppbRoute
  '/retailer/jobs': typeof RetailerJobsRouteWithChildren
  '/retailer/kyc': typeof RetailerKycRoute
  '/retailer/matrimony': typeof RetailerMatrimonyRoute
  '/retailer/money-transfer': typeof RetailerMoneyTransferRoute
  '/retailer/my-services': typeof RetailerMyServicesRoute
  '/retailer/page-tools': typeof RetailerPageToolsRoute
  '/retailer/pan-portal': typeof RetailerPanPortalRoute
  '/retailer/profile': typeof RetailerProfileRoute
  '/retailer/recharge': typeof RetailerRechargeRoute
  '/retailer/referrals': typeof RetailerReferralsRoute
  '/retailer/services': typeof RetailerServicesRoute
  '/retailer/staff': typeof RetailerStaffRoute
  '/retailer/training-guide': typeof RetailerTrainingGuideRoute
  '/retailer/trainings': typeof RetailerTrainingsRoute
  '/retailer/transactions': typeof RetailerTransactionsRoute
  '/retailer/virtual-trainer': typeof RetailerVirtualTrainerRoute
  '/retailer/wallet': typeof RetailerWalletRoute
  '/retailer/work': typeof RetailerWorkRoute
  '/retailer/work-badge': typeof RetailerWorkBadgeRoute
  '/staff/dmt': typeof StaffDmtRoute
  '/staff/form-submissions': typeof StaffFormSubmissionsRoute
  '/staff/forms': typeof StaffFormsRoute
  '/staff/horoscope-requests': typeof StaffHoroscopeRequestsRoute
  '/staff/ippb': typeof StaffIppbRoute
  '/staff/leads': typeof StaffLeadsRoute
  '/staff/performance': typeof StaffPerformanceRoute
  '/staff/reports': typeof StaffReportsRoute
  '/staff/services': typeof StaffServicesRoute
  '/trainer/trainings': typeof TrainerTrainingsRoute
  '/trainer/wallet': typeof TrainerWalletRoute
  '/worker/$workerId': typeof WorkerWorkerIdRoute
  '/admin/': typeof AdminIndexRoute
  '/distributor/': typeof DistributorIndexRoute
  '/matrimony/': typeof MatrimonyIndexRoute
  '/operator/': typeof OperatorIndexRoute
  '/retailer/': typeof RetailerIndexRoute
  '/staff/': typeof StaffIndexRoute
  '/trainer/': typeof TrainerIndexRoute
  '/retailer/jobs/$jobId': typeof RetailerJobsJobIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/booklet': typeof BookletRoute
  '/install': typeof InstallRoute
  '/login': typeof LoginRoute
  '/nsdl-callback': typeof NsdlCallbackRoute
  '/register': typeof RegisterRoute
  '/welcome': typeof WelcomeRoute
  '/admin/certificate-reissues': typeof AdminCertificateReissuesRoute
  '/admin/chat-inbox': typeof AdminChatInboxRoute
  '/admin/commissions': typeof AdminCommissionsRoute
  '/admin/create-user': typeof AdminCreateUserRoute
  '/admin/crm-leads': typeof AdminCrmLeadsRoute
  '/admin/crm-reports': typeof AdminCrmReportsRoute
  '/admin/csc-monitor': typeof AdminCscMonitorRoute
  '/admin/csc-settings': typeof AdminCscSettingsRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/form-analytics': typeof AdminFormAnalyticsRoute
  '/admin/horoscope-settings': typeof AdminHoroscopeSettingsRoute
  '/admin/ippb-badges': typeof AdminIppbBadgesRoute
  '/admin/ippb-settings': typeof AdminIppbSettingsRoute
  '/admin/job-disputes': typeof AdminJobDisputesRoute
  '/admin/job-earnings': typeof AdminJobEarningsRoute
  '/admin/job-marketplace': typeof AdminJobMarketplaceRoute
  '/admin/kyc': typeof AdminKycRoute
  '/admin/landing-cms': typeof AdminLandingCmsRoute
  '/admin/matrimony': typeof AdminMatrimonyRoute
  '/admin/notices': typeof AdminNoticesRoute
  '/admin/pan-settings': typeof AdminPanSettingsRoute
  '/admin/psa-ids': typeof AdminPsaIdsRoute
  '/admin/recharge-transactions': typeof AdminRechargeTransactionsRoute
  '/admin/referrals': typeof AdminReferralsRoute
  '/admin/service-activations': typeof AdminServiceActivationsRoute
  '/admin/service-activations-config': typeof AdminServiceActivationsConfigRoute
  '/admin/service-buttons': typeof AdminServiceButtonsRoute
  '/admin/service-plans': typeof AdminServicePlansRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/session-quality': typeof AdminSessionQualityRoute
  '/admin/training-earnings': typeof AdminTrainingEarningsRoute
  '/admin/training-reviews': typeof AdminTrainingReviewsRoute
  '/admin/training-settings': typeof AdminTrainingSettingsRoute
  '/admin/trainings': typeof AdminTrainingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/wallet-requests': typeof AdminWalletRequestsRoute
  '/admin/wallets': typeof AdminWalletsRoute
  '/admin/work-badges': typeof AdminWorkBadgesRoute
  '/distributor/earnings': typeof DistributorEarningsRoute
  '/distributor/wallet': typeof DistributorWalletRoute
  '/matrimony/$profileId': typeof MatrimonyProfileIdRoute
  '/retailer/activate': typeof RetailerActivateRoute
  '/retailer/cv-builder': typeof RetailerCvBuilderRoute
  '/retailer/ei-pay': typeof RetailerEiPayRoute
  '/retailer/finance': typeof RetailerFinanceRoute
  '/retailer/forms': typeof RetailerFormsRoute
  '/retailer/horoscope': typeof RetailerHoroscopeRoute
  '/retailer/ippb': typeof RetailerIppbRoute
  '/retailer/jobs': typeof RetailerJobsRouteWithChildren
  '/retailer/kyc': typeof RetailerKycRoute
  '/retailer/matrimony': typeof RetailerMatrimonyRoute
  '/retailer/money-transfer': typeof RetailerMoneyTransferRoute
  '/retailer/my-services': typeof RetailerMyServicesRoute
  '/retailer/page-tools': typeof RetailerPageToolsRoute
  '/retailer/pan-portal': typeof RetailerPanPortalRoute
  '/retailer/profile': typeof RetailerProfileRoute
  '/retailer/recharge': typeof RetailerRechargeRoute
  '/retailer/referrals': typeof RetailerReferralsRoute
  '/retailer/services': typeof RetailerServicesRoute
  '/retailer/staff': typeof RetailerStaffRoute
  '/retailer/training-guide': typeof RetailerTrainingGuideRoute
  '/retailer/trainings': typeof RetailerTrainingsRoute
  '/retailer/transactions': typeof RetailerTransactionsRoute
  '/retailer/virtual-trainer': typeof RetailerVirtualTrainerRoute
  '/retailer/wallet': typeof RetailerWalletRoute
  '/retailer/work': typeof RetailerWorkRoute
  '/retailer/work-badge': typeof RetailerWorkBadgeRoute
  '/staff/dmt': typeof StaffDmtRoute
  '/staff/form-submissions': typeof StaffFormSubmissionsRoute
  '/staff/forms': typeof StaffFormsRoute
  '/staff/horoscope-requests': typeof StaffHoroscopeRequestsRoute
  '/staff/ippb': typeof StaffIppbRoute
  '/staff/leads': typeof StaffLeadsRoute
  '/staff/performance': typeof StaffPerformanceRoute
  '/staff/reports': typeof StaffReportsRoute
  '/staff/services': typeof StaffServicesRoute
  '/trainer/trainings': typeof TrainerTrainingsRoute
  '/trainer/wallet': typeof TrainerWalletRoute
  '/worker/$workerId': typeof WorkerWorkerIdRoute
  '/admin': typeof AdminIndexRoute
  '/distributor': typeof DistributorIndexRoute
  '/matrimony': typeof MatrimonyIndexRoute
  '/operator': typeof OperatorIndexRoute
  '/retailer': typeof RetailerIndexRoute
  '/staff': typeof StaffIndexRoute
  '/trainer': typeof TrainerIndexRoute
  '/retailer/jobs/$jobId': typeof RetailerJobsJobIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/booklet': typeof BookletRoute
  '/distributor': typeof DistributorRouteWithChildren
  '/install': typeof InstallRoute
  '/login': typeof LoginRoute
  '/matrimony': typeof MatrimonyRouteWithChildren
  '/nsdl-callback': typeof NsdlCallbackRoute
  '/operator': typeof OperatorRouteWithChildren
  '/register': typeof RegisterRoute
  '/retailer': typeof RetailerRouteWithChildren
  '/staff': typeof StaffRouteWithChildren
  '/trainer': typeof TrainerRouteWithChildren
  '/welcome': typeof WelcomeRoute
  '/admin/certificate-reissues': typeof AdminCertificateReissuesRoute
  '/admin/chat-inbox': typeof AdminChatInboxRoute
  '/admin/commissions': typeof AdminCommissionsRoute
  '/admin/create-user': typeof AdminCreateUserRoute
  '/admin/crm-leads': typeof AdminCrmLeadsRoute
  '/admin/crm-reports': typeof AdminCrmReportsRoute
  '/admin/csc-monitor': typeof AdminCscMonitorRoute
  '/admin/csc-settings': typeof AdminCscSettingsRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/form-analytics': typeof AdminFormAnalyticsRoute
  '/admin/horoscope-settings': typeof AdminHoroscopeSettingsRoute
  '/admin/ippb-badges': typeof AdminIppbBadgesRoute
  '/admin/ippb-settings': typeof AdminIppbSettingsRoute
  '/admin/job-disputes': typeof AdminJobDisputesRoute
  '/admin/job-earnings': typeof AdminJobEarningsRoute
  '/admin/job-marketplace': typeof AdminJobMarketplaceRoute
  '/admin/kyc': typeof AdminKycRoute
  '/admin/landing-cms': typeof AdminLandingCmsRoute
  '/admin/matrimony': typeof AdminMatrimonyRoute
  '/admin/notices': typeof AdminNoticesRoute
  '/admin/pan-settings': typeof AdminPanSettingsRoute
  '/admin/psa-ids': typeof AdminPsaIdsRoute
  '/admin/recharge-transactions': typeof AdminRechargeTransactionsRoute
  '/admin/referrals': typeof AdminReferralsRoute
  '/admin/service-activations': typeof AdminServiceActivationsRoute
  '/admin/service-activations-config': typeof AdminServiceActivationsConfigRoute
  '/admin/service-buttons': typeof AdminServiceButtonsRoute
  '/admin/service-plans': typeof AdminServicePlansRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/session-quality': typeof AdminSessionQualityRoute
  '/admin/training-earnings': typeof AdminTrainingEarningsRoute
  '/admin/training-reviews': typeof AdminTrainingReviewsRoute
  '/admin/training-settings': typeof AdminTrainingSettingsRoute
  '/admin/trainings': typeof AdminTrainingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/wallet-requests': typeof AdminWalletRequestsRoute
  '/admin/wallets': typeof AdminWalletsRoute
  '/admin/work-badges': typeof AdminWorkBadgesRoute
  '/distributor/earnings': typeof DistributorEarningsRoute
  '/distributor/wallet': typeof DistributorWalletRoute
  '/matrimony/$profileId': typeof MatrimonyProfileIdRoute
  '/retailer/activate': typeof RetailerActivateRoute
  '/retailer/cv-builder': typeof RetailerCvBuilderRoute
  '/retailer/ei-pay': typeof RetailerEiPayRoute
  '/retailer/finance': typeof RetailerFinanceRoute
  '/retailer/forms': typeof RetailerFormsRoute
  '/retailer/horoscope': typeof RetailerHoroscopeRoute
  '/retailer/ippb': typeof RetailerIppbRoute
  '/retailer/jobs': typeof RetailerJobsRouteWithChildren
  '/retailer/kyc': typeof RetailerKycRoute
  '/retailer/matrimony': typeof RetailerMatrimonyRoute
  '/retailer/money-transfer': typeof RetailerMoneyTransferRoute
  '/retailer/my-services': typeof RetailerMyServicesRoute
  '/retailer/page-tools': typeof RetailerPageToolsRoute
  '/retailer/pan-portal': typeof RetailerPanPortalRoute
  '/retailer/profile': typeof RetailerProfileRoute
  '/retailer/recharge': typeof RetailerRechargeRoute
  '/retailer/referrals': typeof RetailerReferralsRoute
  '/retailer/services': typeof RetailerServicesRoute
  '/retailer/staff': typeof RetailerStaffRoute
  '/retailer/training-guide': typeof RetailerTrainingGuideRoute
  '/retailer/trainings': typeof RetailerTrainingsRoute
  '/retailer/transactions': typeof RetailerTransactionsRoute
  '/retailer/virtual-trainer': typeof RetailerVirtualTrainerRoute
  '/retailer/wallet': typeof RetailerWalletRoute
  '/retailer/work': typeof RetailerWorkRoute
  '/retailer/work-badge': typeof RetailerWorkBadgeRoute
  '/staff/dmt': typeof StaffDmtRoute
  '/staff/form-submissions': typeof StaffFormSubmissionsRoute
  '/staff/forms': typeof StaffFormsRoute
  '/staff/horoscope-requests': typeof StaffHoroscopeRequestsRoute
  '/staff/ippb': typeof StaffIppbRoute
  '/staff/leads': typeof StaffLeadsRoute
  '/staff/performance': typeof StaffPerformanceRoute
  '/staff/reports': typeof StaffReportsRoute
  '/staff/services': typeof StaffServicesRoute
  '/trainer/trainings': typeof TrainerTrainingsRoute
  '/trainer/wallet': typeof TrainerWalletRoute
  '/worker/$workerId': typeof WorkerWorkerIdRoute
  '/admin/': typeof AdminIndexRoute
  '/distributor/': typeof DistributorIndexRoute
  '/matrimony/': typeof MatrimonyIndexRoute
  '/operator/': typeof OperatorIndexRoute
  '/retailer/': typeof RetailerIndexRoute
  '/staff/': typeof StaffIndexRoute
  '/trainer/': typeof TrainerIndexRoute
  '/retailer/jobs/$jobId': typeof RetailerJobsJobIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/booklet'
    | '/distributor'
    | '/install'
    | '/login'
    | '/matrimony'
    | '/nsdl-callback'
    | '/operator'
    | '/register'
    | '/retailer'
    | '/staff'
    | '/trainer'
    | '/welcome'
    | '/admin/certificate-reissues'
    | '/admin/chat-inbox'
    | '/admin/commissions'
    | '/admin/create-user'
    | '/admin/crm-leads'
    | '/admin/crm-reports'
    | '/admin/csc-monitor'
    | '/admin/csc-settings'
    | '/admin/finance'
    | '/admin/form-analytics'
    | '/admin/horoscope-settings'
    | '/admin/ippb-badges'
    | '/admin/ippb-settings'
    | '/admin/job-disputes'
    | '/admin/job-earnings'
    | '/admin/job-marketplace'
    | '/admin/kyc'
    | '/admin/landing-cms'
    | '/admin/matrimony'
    | '/admin/notices'
    | '/admin/pan-settings'
    | '/admin/psa-ids'
    | '/admin/recharge-transactions'
    | '/admin/referrals'
    | '/admin/service-activations'
    | '/admin/service-activations-config'
    | '/admin/service-buttons'
    | '/admin/service-plans'
    | '/admin/services'
    | '/admin/session-quality'
    | '/admin/training-earnings'
    | '/admin/training-reviews'
    | '/admin/training-settings'
    | '/admin/trainings'
    | '/admin/users'
    | '/admin/wallet-requests'
    | '/admin/wallets'
    | '/admin/work-badges'
    | '/distributor/earnings'
    | '/distributor/wallet'
    | '/matrimony/$profileId'
    | '/retailer/activate'
    | '/retailer/cv-builder'
    | '/retailer/ei-pay'
    | '/retailer/finance'
    | '/retailer/forms'
    | '/retailer/horoscope'
    | '/retailer/ippb'
    | '/retailer/jobs'
    | '/retailer/kyc'
    | '/retailer/matrimony'
    | '/retailer/money-transfer'
    | '/retailer/my-services'
    | '/retailer/page-tools'
    | '/retailer/pan-portal'
    | '/retailer/profile'
    | '/retailer/recharge'
    | '/retailer/referrals'
    | '/retailer/services'
    | '/retailer/staff'
    | '/retailer/training-guide'
    | '/retailer/trainings'
    | '/retailer/transactions'
    | '/retailer/virtual-trainer'
    | '/retailer/wallet'
    | '/retailer/work'
    | '/retailer/work-badge'
    | '/staff/dmt'
    | '/staff/form-submissions'
    | '/staff/forms'
    | '/staff/horoscope-requests'
    | '/staff/ippb'
    | '/staff/leads'
    | '/staff/performance'
    | '/staff/reports'
    | '/staff/services'
    | '/trainer/trainings'
    | '/trainer/wallet'
    | '/worker/$workerId'
    | '/admin/'
    | '/distributor/'
    | '/matrimony/'
    | '/operator/'
    | '/retailer/'
    | '/staff/'
    | '/trainer/'
    | '/retailer/jobs/$jobId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/booklet'
    | '/install'
    | '/login'
    | '/nsdl-callback'
    | '/register'
    | '/welcome'
    | '/admin/certificate-reissues'
    | '/admin/chat-inbox'
    | '/admin/commissions'
    | '/admin/create-user'
    | '/admin/crm-leads'
    | '/admin/crm-reports'
    | '/admin/csc-monitor'
    | '/admin/csc-settings'
    | '/admin/finance'
    | '/admin/form-analytics'
    | '/admin/horoscope-settings'
    | '/admin/ippb-badges'
    | '/admin/ippb-settings'
    | '/admin/job-disputes'
    | '/admin/job-earnings'
    | '/admin/job-marketplace'
    | '/admin/kyc'
    | '/admin/landing-cms'
    | '/admin/matrimony'
    | '/admin/notices'
    | '/admin/pan-settings'
    | '/admin/psa-ids'
    | '/admin/recharge-transactions'
    | '/admin/referrals'
    | '/admin/service-activations'
    | '/admin/service-activations-config'
    | '/admin/service-buttons'
    | '/admin/service-plans'
    | '/admin/services'
    | '/admin/session-quality'
    | '/admin/training-earnings'
    | '/admin/training-reviews'
    | '/admin/training-settings'
    | '/admin/trainings'
    | '/admin/users'
    | '/admin/wallet-requests'
    | '/admin/wallets'
    | '/admin/work-badges'
    | '/distributor/earnings'
    | '/distributor/wallet'
    | '/matrimony/$profileId'
    | '/retailer/activate'
    | '/retailer/cv-builder'
    | '/retailer/ei-pay'
    | '/retailer/finance'
    | '/retailer/forms'
    | '/retailer/horoscope'
    | '/retailer/ippb'
    | '/retailer/jobs'
    | '/retailer/kyc'
    | '/retailer/matrimony'
    | '/retailer/money-transfer'
    | '/retailer/my-services'
    | '/retailer/page-tools'
    | '/retailer/pan-portal'
    | '/retailer/profile'
    | '/retailer/recharge'
    | '/retailer/referrals'
    | '/retailer/services'
    | '/retailer/staff'
    | '/retailer/training-guide'
    | '/retailer/trainings'
    | '/retailer/transactions'
    | '/retailer/virtual-trainer'
    | '/retailer/wallet'
    | '/retailer/work'
    | '/retailer/work-badge'
    | '/staff/dmt'
    | '/staff/form-submissions'
    | '/staff/forms'
    | '/staff/horoscope-requests'
    | '/staff/ippb'
    | '/staff/leads'
    | '/staff/performance'
    | '/staff/reports'
    | '/staff/services'
    | '/trainer/trainings'
    | '/trainer/wallet'
    | '/worker/$workerId'
    | '/admin'
    | '/distributor'
    | '/matrimony'
    | '/operator'
    | '/retailer'
    | '/staff'
    | '/trainer'
    | '/retailer/jobs/$jobId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/booklet'
    | '/distributor'
    | '/install'
    | '/login'
    | '/matrimony'
    | '/nsdl-callback'
    | '/operator'
    | '/register'
    | '/retailer'
    | '/staff'
    | '/trainer'
    | '/welcome'
    | '/admin/certificate-reissues'
    | '/admin/chat-inbox'
    | '/admin/commissions'
    | '/admin/create-user'
    | '/admin/crm-leads'
    | '/admin/crm-reports'
    | '/admin/csc-monitor'
    | '/admin/csc-settings'
    | '/admin/finance'
    | '/admin/form-analytics'
    | '/admin/horoscope-settings'
    | '/admin/ippb-badges'
    | '/admin/ippb-settings'
    | '/admin/job-disputes'
    | '/admin/job-earnings'
    | '/admin/job-marketplace'
    | '/admin/kyc'
    | '/admin/landing-cms'
    | '/admin/matrimony'
    | '/admin/notices'
    | '/admin/pan-settings'
    | '/admin/psa-ids'
    | '/admin/recharge-transactions'
    | '/admin/referrals'
    | '/admin/service-activations'
    | '/admin/service-activations-config'
    | '/admin/service-buttons'
    | '/admin/service-plans'
    | '/admin/services'
    | '/admin/session-quality'
    | '/admin/training-earnings'
    | '/admin/training-reviews'
    | '/admin/training-settings'
    | '/admin/trainings'
    | '/admin/users'
    | '/admin/wallet-requests'
    | '/admin/wallets'
    | '/admin/work-badges'
    | '/distributor/earnings'
    | '/distributor/wallet'
    | '/matrimony/$profileId'
    | '/retailer/activate'
    | '/retailer/cv-builder'
    | '/retailer/ei-pay'
    | '/retailer/finance'
    | '/retailer/forms'
    | '/retailer/horoscope'
    | '/retailer/ippb'
    | '/retailer/jobs'
    | '/retailer/kyc'
    | '/retailer/matrimony'
    | '/retailer/money-transfer'
    | '/retailer/my-services'
    | '/retailer/page-tools'
    | '/retailer/pan-portal'
    | '/retailer/profile'
    | '/retailer/recharge'
    | '/retailer/referrals'
    | '/retailer/services'
    | '/retailer/staff'
    | '/retailer/training-guide'
    | '/retailer/trainings'
    | '/retailer/transactions'
    | '/retailer/virtual-trainer'
    | '/retailer/wallet'
    | '/retailer/work'
    | '/retailer/work-badge'
    | '/staff/dmt'
    | '/staff/form-submissions'
    | '/staff/forms'
    | '/staff/horoscope-requests'
    | '/staff/ippb'
    | '/staff/leads'
    | '/staff/performance'
    | '/staff/reports'
    | '/staff/services'
    | '/trainer/trainings'
    | '/trainer/wallet'
    | '/worker/$workerId'
    | '/admin/'
    | '/distributor/'
    | '/matrimony/'
    | '/operator/'
    | '/retailer/'
    | '/staff/'
    | '/trainer/'
    | '/retailer/jobs/$jobId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  BookletRoute: typeof BookletRoute
  DistributorRoute: typeof DistributorRouteWithChildren
  InstallRoute: typeof InstallRoute
  LoginRoute: typeof LoginRoute
  MatrimonyRoute: typeof MatrimonyRouteWithChildren
  NsdlCallbackRoute: typeof NsdlCallbackRoute
  OperatorRoute: typeof OperatorRouteWithChildren
  RegisterRoute: typeof RegisterRoute
  RetailerRoute: typeof RetailerRouteWithChildren
  StaffRoute: typeof StaffRouteWithChildren
  TrainerRoute: typeof TrainerRouteWithChildren
  WelcomeRoute: typeof WelcomeRoute
  WorkerWorkerIdRoute: typeof WorkerWorkerIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trainer': {
      id: '/trainer'
      path: '/trainer'
      fullPath: '/trainer'
      preLoaderRoute: typeof TrainerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/retailer': {
      id: '/retailer'
      path: '/retailer'
      fullPath: '/retailer'
      preLoaderRoute: typeof RetailerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operator': {
      id: '/operator'
      path: '/operator'
      fullPath: '/operator'
      preLoaderRoute: typeof OperatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nsdl-callback': {
      id: '/nsdl-callback'
      path: '/nsdl-callback'
      fullPath: '/nsdl-callback'
      preLoaderRoute: typeof NsdlCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matrimony': {
      id: '/matrimony'
      path: '/matrimony'
      fullPath: '/matrimony'
      preLoaderRoute: typeof MatrimonyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/install': {
      id: '/install'
      path: '/install'
      fullPath: '/install'
      preLoaderRoute: typeof InstallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/distributor': {
      id: '/distributor'
      path: '/distributor'
      fullPath: '/distributor'
      preLoaderRoute: typeof DistributorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booklet': {
      id: '/booklet'
      path: '/booklet'
      fullPath: '/booklet'
      preLoaderRoute: typeof BookletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trainer/': {
      id: '/trainer/'
      path: '/'
      fullPath: '/trainer/'
      preLoaderRoute: typeof TrainerIndexRouteImport
      parentRoute: typeof TrainerRoute
    }
    '/staff/': {
      id: '/staff/'
      path: '/'
      fullPath: '/staff/'
      preLoaderRoute: typeof StaffIndexRouteImport
      parentRoute: typeof StaffRoute
    }
    '/retailer/': {
      id: '/retailer/'
      path: '/'
      fullPath: '/retailer/'
      preLoaderRoute: typeof RetailerIndexRouteImport
      parentRoute: typeof RetailerRoute
    }
    '/operator/': {
      id: '/operator/'
      path: '/'
      fullPath: '/operator/'
      preLoaderRoute: typeof OperatorIndexRouteImport
      parentRoute: typeof OperatorRoute
    }
    '/matrimony/': {
      id: '/matrimony/'
      path: '/'
      fullPath: '/matrimony/'
      preLoaderRoute: typeof MatrimonyIndexRouteImport
      parentRoute: typeof MatrimonyRoute
    }
    '/distributor/': {
      id: '/distributor/'
      path: '/'
      fullPath: '/distributor/'
      preLoaderRoute: typeof DistributorIndexRouteImport
      parentRoute: typeof DistributorRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/worker/$workerId': {
      id: '/worker/$workerId'
      path: '/worker/$workerId'
      fullPath: '/worker/$workerId'
      preLoaderRoute: typeof WorkerWorkerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trainer/wallet': {
      id: '/trainer/wallet'
      path: '/wallet'
      fullPath: '/trainer/wallet'
      preLoaderRoute: typeof TrainerWalletRouteImport
      parentRoute: typeof TrainerRoute
    }
    '/trainer/trainings': {
      id: '/trainer/trainings'
      path: '/trainings'
      fullPath: '/trainer/trainings'
      preLoaderRoute: typeof TrainerTrainingsRouteImport
      parentRoute: typeof TrainerRoute
    }
    '/staff/services': {
      id: '/staff/services'
      path: '/services'
      fullPath: '/staff/services'
      preLoaderRoute: typeof StaffServicesRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/reports': {
      id: '/staff/reports'
      path: '/reports'
      fullPath: '/staff/reports'
      preLoaderRoute: typeof StaffReportsRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/performance': {
      id: '/staff/performance'
      path: '/performance'
      fullPath: '/staff/performance'
      preLoaderRoute: typeof StaffPerformanceRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/leads': {
      id: '/staff/leads'
      path: '/leads'
      fullPath: '/staff/leads'
      preLoaderRoute: typeof StaffLeadsRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/ippb': {
      id: '/staff/ippb'
      path: '/ippb'
      fullPath: '/staff/ippb'
      preLoaderRoute: typeof StaffIppbRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/horoscope-requests': {
      id: '/staff/horoscope-requests'
      path: '/horoscope-requests'
      fullPath: '/staff/horoscope-requests'
      preLoaderRoute: typeof StaffHoroscopeRequestsRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/forms': {
      id: '/staff/forms'
      path: '/forms'
      fullPath: '/staff/forms'
      preLoaderRoute: typeof StaffFormsRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/form-submissions': {
      id: '/staff/form-submissions'
      path: '/form-submissions'
      fullPath: '/staff/form-submissions'
      preLoaderRoute: typeof StaffFormSubmissionsRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/dmt': {
      id: '/staff/dmt'
      path: '/dmt'
      fullPath: '/staff/dmt'
      preLoaderRoute: typeof StaffDmtRouteImport
      parentRoute: typeof StaffRoute
    }
    '/retailer/work-badge': {
      id: '/retailer/work-badge'
      path: '/work-badge'
      fullPath: '/retailer/work-badge'
      preLoaderRoute: typeof RetailerWorkBadgeRouteImport
      parentRoute: typeof RetailerRoute
    }
    '/retailer/work': {
      id: '/retailer/work'
      path: '/work'
      fullPath: '/retailer/work'
      preLoaderRoute: typeof RetailerWorkRouteImport
      parentRoute: typeof RetailerRoute
    }
    '/retailer/wallet': {
      id: '/retailer/wallet'
      path: '/wallet'
      fullPath: '/retailer/wallet'
      preLoaderRoute: typeof RetailerWalletRouteImport
      parentRoute: typeof RetailerRoute
    }
    '/retailer/virtual-trainer': {
      id: '/retailer/virtual-trainer'
      path: '/virtual-trainer'
      fullPath: '/retailer/virtual-trainer'
      preLoaderRoute: typeof RetailerVirtualTrainerRouteImport
      parentRoute: typeof RetailerRoute
    }
    '/retailer/transactions': {
      id: '/retailer/transactions'
      path: '/transactions'
      fullPath: '/retailer/transactions'
      preLoaderRoute: typeof RetailerTransactionsRouteImport
      parentRoute: typeof RetailerRoute
    }
    '/retailer/trainings': {
      id: '/retailer/trainings'
      path: '/trainings'
      fullPath: '/retailer/trainings'
      preLoaderRoute: typeof RetailerTrainingsRouteImport
      parentRoute: typeof RetailerRoute
    }
    '/retailer/training-guide': {
      id: '/retailer/training-guide'
      path: '/training-guide'
      fullPath: '/retailer/training-guide'
      preLoaderRoute: typeof RetailerTrainingGuideRouteImport
      parentRoute: typeof RetailerRoute
    }
    '/retailer/staff': {
      id: '/retailer/staff'
      path: '/staff'
      fullPath: '/retailer/staff'
      preLoaderRoute: typeof RetailerStaffRouteImport
      parentRoute: typeof RetailerRoute
    }
    '/retailer/services': {
      id: '/retailer/services'
      path: '/services'
      fullPath: '/retailer/services'
      preLoaderRoute: typeof RetailerServicesRouteImport
      parentRoute: typeof RetailerRoute
    }
    '/retailer/referrals': {
      id: '/retailer/referrals'
      path: '/referrals'
      fullPath: '/retailer/referrals'
      preLoaderRoute: typeof RetailerReferralsRouteImport
      parentRoute: typeof RetailerRoute
    }
    '/retailer/recharge': {
      id: '/retailer/recharge'
      path: '/recharge'
      fullPath: '/retailer/recharge'
      preLoaderRoute: typeof RetailerRechargeRouteImport
      parentRoute: typeof RetailerRoute
    }
    '/retailer/profile': {
      id: '/retailer/profile'
      path: '/profile'
      fullPath: '/retailer/profile'
      preLoaderRoute: typeof RetailerProfileRouteImport
      parentRoute: typeof RetailerRoute
    }
    '/retailer/pan-portal': {
      id: '/retailer/pan-portal'
      path: '/pan-portal'
      fullPath: '/retailer/pan-portal'
      preLoaderRoute: typeof RetailerPanPortalRouteImport
      parentRoute: typeof RetailerRoute
    }
    '/retailer/page-tools': {
      id: '/retailer/page-tools'
      path: '/page-tools'
      fullPath: '/retailer/page-tools'
      preLoaderRoute: typeof RetailerPageToolsRouteImport
      parentRoute: typeof RetailerRoute
    }
    '/retailer/my-services': {
      id: '/retailer/my-services'
      path: '/my-services'
      fullPath: '/retailer/my-services'
      preLoaderRoute: typeof RetailerMyServicesRouteImport
      parentRoute: typeof RetailerRoute
    }
    '/retailer/money-transfer': {
      id: '/retailer/money-transfer'
      path: '/money-transfer'
      fullPath: '/retailer/money-transfer'
      preLoaderRoute: typeof RetailerMoneyTransferRouteImport
      parentRoute: typeof RetailerRoute
    }
    '/retailer/matrimony': {
      id: '/retailer/matrimony'
      path: '/matrimony'
      fullPath: '/retailer/matrimony'
      preLoaderRoute: typeof RetailerMatrimonyRouteImport
      parentRoute: typeof RetailerRoute
    }
    '/retailer/kyc': {
      id: '/retailer/kyc'
      path: '/kyc'
      fullPath: '/retailer/kyc'
      preLoaderRoute: typeof RetailerKycRouteImport
      parentRoute: typeof RetailerRoute
    }
    '/retailer/jobs': {
      id: '/retailer/jobs'
      path: '/jobs'
      fullPath: '/retailer/jobs'
      preLoaderRoute: typeof RetailerJobsRouteImport
      parentRoute: typeof RetailerRoute
    }
    '/retailer/ippb': {
      id: '/retailer/ippb'
      path: '/ippb'
      fullPath: '/retailer/ippb'
      preLoaderRoute: typeof RetailerIppbRouteImport
      parentRoute: typeof RetailerRoute
    }
    '/retailer/horoscope': {
      id: '/retailer/horoscope'
      path: '/horoscope'
      fullPath: '/retailer/horoscope'
      preLoaderRoute: typeof RetailerHoroscopeRouteImport
      parentRoute: typeof RetailerRoute
    }
    '/retailer/forms': {
      id: '/retailer/forms'
      path: '/forms'
      fullPath: '/retailer/forms'
      preLoaderRoute: typeof RetailerFormsRouteImport
      parentRoute: typeof RetailerRoute
    }
    '/retailer/finance': {
      id: '/retailer/finance'
      path: '/finance'
      fullPath: '/retailer/finance'
      preLoaderRoute: typeof RetailerFinanceRouteImport
      parentRoute: typeof RetailerRoute
    }
    '/retailer/ei-pay': {
      id: '/retailer/ei-pay'
      path: '/ei-pay'
      fullPath: '/retailer/ei-pay'
      preLoaderRoute: typeof RetailerEiPayRouteImport
      parentRoute: typeof RetailerRoute
    }
    '/retailer/cv-builder': {
      id: '/retailer/cv-builder'
      path: '/cv-builder'
      fullPath: '/retailer/cv-builder'
      preLoaderRoute: typeof RetailerCvBuilderRouteImport
      parentRoute: typeof RetailerRoute
    }
    '/retailer/activate': {
      id: '/retailer/activate'
      path: '/activate'
      fullPath: '/retailer/activate'
      preLoaderRoute: typeof RetailerActivateRouteImport
      parentRoute: typeof RetailerRoute
    }
    '/matrimony/$profileId': {
      id: '/matrimony/$profileId'
      path: '/$profileId'
      fullPath: '/matrimony/$profileId'
      preLoaderRoute: typeof MatrimonyProfileIdRouteImport
      parentRoute: typeof MatrimonyRoute
    }
    '/distributor/wallet': {
      id: '/distributor/wallet'
      path: '/wallet'
      fullPath: '/distributor/wallet'
      preLoaderRoute: typeof DistributorWalletRouteImport
      parentRoute: typeof DistributorRoute
    }
    '/distributor/earnings': {
      id: '/distributor/earnings'
      path: '/earnings'
      fullPath: '/distributor/earnings'
      preLoaderRoute: typeof DistributorEarningsRouteImport
      parentRoute: typeof DistributorRoute
    }
    '/admin/work-badges': {
      id: '/admin/work-badges'
      path: '/work-badges'
      fullPath: '/admin/work-badges'
      preLoaderRoute: typeof AdminWorkBadgesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/wallets': {
      id: '/admin/wallets'
      path: '/wallets'
      fullPath: '/admin/wallets'
      preLoaderRoute: typeof AdminWalletsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/wallet-requests': {
      id: '/admin/wallet-requests'
      path: '/wallet-requests'
      fullPath: '/admin/wallet-requests'
      preLoaderRoute: typeof AdminWalletRequestsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/trainings': {
      id: '/admin/trainings'
      path: '/trainings'
      fullPath: '/admin/trainings'
      preLoaderRoute: typeof AdminTrainingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/training-settings': {
      id: '/admin/training-settings'
      path: '/training-settings'
      fullPath: '/admin/training-settings'
      preLoaderRoute: typeof AdminTrainingSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/training-reviews': {
      id: '/admin/training-reviews'
      path: '/training-reviews'
      fullPath: '/admin/training-reviews'
      preLoaderRoute: typeof AdminTrainingReviewsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/training-earnings': {
      id: '/admin/training-earnings'
      path: '/training-earnings'
      fullPath: '/admin/training-earnings'
      preLoaderRoute: typeof AdminTrainingEarningsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/session-quality': {
      id: '/admin/session-quality'
      path: '/session-quality'
      fullPath: '/admin/session-quality'
      preLoaderRoute: typeof AdminSessionQualityRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/services': {
      id: '/admin/services'
      path: '/services'
      fullPath: '/admin/services'
      preLoaderRoute: typeof AdminServicesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/service-plans': {
      id: '/admin/service-plans'
      path: '/service-plans'
      fullPath: '/admin/service-plans'
      preLoaderRoute: typeof AdminServicePlansRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/service-buttons': {
      id: '/admin/service-buttons'
      path: '/service-buttons'
      fullPath: '/admin/service-buttons'
      preLoaderRoute: typeof AdminServiceButtonsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/service-activations-config': {
      id: '/admin/service-activations-config'
      path: '/service-activations-config'
      fullPath: '/admin/service-activations-config'
      preLoaderRoute: typeof AdminServiceActivationsConfigRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/service-activations': {
      id: '/admin/service-activations'
      path: '/service-activations'
      fullPath: '/admin/service-activations'
      preLoaderRoute: typeof AdminServiceActivationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/referrals': {
      id: '/admin/referrals'
      path: '/referrals'
      fullPath: '/admin/referrals'
      preLoaderRoute: typeof AdminReferralsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/recharge-transactions': {
      id: '/admin/recharge-transactions'
      path: '/recharge-transactions'
      fullPath: '/admin/recharge-transactions'
      preLoaderRoute: typeof AdminRechargeTransactionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/psa-ids': {
      id: '/admin/psa-ids'
      path: '/psa-ids'
      fullPath: '/admin/psa-ids'
      preLoaderRoute: typeof AdminPsaIdsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pan-settings': {
      id: '/admin/pan-settings'
      path: '/pan-settings'
      fullPath: '/admin/pan-settings'
      preLoaderRoute: typeof AdminPanSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notices': {
      id: '/admin/notices'
      path: '/notices'
      fullPath: '/admin/notices'
      preLoaderRoute: typeof AdminNoticesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/matrimony': {
      id: '/admin/matrimony'
      path: '/matrimony'
      fullPath: '/admin/matrimony'
      preLoaderRoute: typeof AdminMatrimonyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/landing-cms': {
      id: '/admin/landing-cms'
      path: '/landing-cms'
      fullPath: '/admin/landing-cms'
      preLoaderRoute: typeof AdminLandingCmsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/kyc': {
      id: '/admin/kyc'
      path: '/kyc'
      fullPath: '/admin/kyc'
      preLoaderRoute: typeof AdminKycRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/job-marketplace': {
      id: '/admin/job-marketplace'
      path: '/job-marketplace'
      fullPath: '/admin/job-marketplace'
      preLoaderRoute: typeof AdminJobMarketplaceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/job-earnings': {
      id: '/admin/job-earnings'
      path: '/job-earnings'
      fullPath: '/admin/job-earnings'
      preLoaderRoute: typeof AdminJobEarningsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/job-disputes': {
      id: '/admin/job-disputes'
      path: '/job-disputes'
      fullPath: '/admin/job-disputes'
      preLoaderRoute: typeof AdminJobDisputesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ippb-settings': {
      id: '/admin/ippb-settings'
      path: '/ippb-settings'
      fullPath: '/admin/ippb-settings'
      preLoaderRoute: typeof AdminIppbSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ippb-badges': {
      id: '/admin/ippb-badges'
      path: '/ippb-badges'
      fullPath: '/admin/ippb-badges'
      preLoaderRoute: typeof AdminIppbBadgesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/horoscope-settings': {
      id: '/admin/horoscope-settings'
      path: '/horoscope-settings'
      fullPath: '/admin/horoscope-settings'
      preLoaderRoute: typeof AdminHoroscopeSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/form-analytics': {
      id: '/admin/form-analytics'
      path: '/form-analytics'
      fullPath: '/admin/form-analytics'
      preLoaderRoute: typeof AdminFormAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/finance': {
      id: '/admin/finance'
      path: '/finance'
      fullPath: '/admin/finance'
      preLoaderRoute: typeof AdminFinanceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/csc-settings': {
      id: '/admin/csc-settings'
      path: '/csc-settings'
      fullPath: '/admin/csc-settings'
      preLoaderRoute: typeof AdminCscSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/csc-monitor': {
      id: '/admin/csc-monitor'
      path: '/csc-monitor'
      fullPath: '/admin/csc-monitor'
      preLoaderRoute: typeof AdminCscMonitorRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/crm-reports': {
      id: '/admin/crm-reports'
      path: '/crm-reports'
      fullPath: '/admin/crm-reports'
      preLoaderRoute: typeof AdminCrmReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/crm-leads': {
      id: '/admin/crm-leads'
      path: '/crm-leads'
      fullPath: '/admin/crm-leads'
      preLoaderRoute: typeof AdminCrmLeadsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/create-user': {
      id: '/admin/create-user'
      path: '/create-user'
      fullPath: '/admin/create-user'
      preLoaderRoute: typeof AdminCreateUserRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/commissions': {
      id: '/admin/commissions'
      path: '/commissions'
      fullPath: '/admin/commissions'
      preLoaderRoute: typeof AdminCommissionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/chat-inbox': {
      id: '/admin/chat-inbox'
      path: '/chat-inbox'
      fullPath: '/admin/chat-inbox'
      preLoaderRoute: typeof AdminChatInboxRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/certificate-reissues': {
      id: '/admin/certificate-reissues'
      path: '/certificate-reissues'
      fullPath: '/admin/certificate-reissues'
      preLoaderRoute: typeof AdminCertificateReissuesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/retailer/jobs/$jobId': {
      id: '/retailer/jobs/$jobId'
      path: '/$jobId'
      fullPath: '/retailer/jobs/$jobId'
      preLoaderRoute: typeof RetailerJobsJobIdRouteImport
      parentRoute: typeof RetailerJobsRoute
    }
  }
}

interface AdminRouteChildren {
  AdminCertificateReissuesRoute: typeof AdminCertificateReissuesRoute
  AdminChatInboxRoute: typeof AdminChatInboxRoute
  AdminCommissionsRoute: typeof AdminCommissionsRoute
  AdminCreateUserRoute: typeof AdminCreateUserRoute
  AdminCrmLeadsRoute: typeof AdminCrmLeadsRoute
  AdminCrmReportsRoute: typeof AdminCrmReportsRoute
  AdminCscMonitorRoute: typeof AdminCscMonitorRoute
  AdminCscSettingsRoute: typeof AdminCscSettingsRoute
  AdminFinanceRoute: typeof AdminFinanceRoute
  AdminFormAnalyticsRoute: typeof AdminFormAnalyticsRoute
  AdminHoroscopeSettingsRoute: typeof AdminHoroscopeSettingsRoute
  AdminIppbBadgesRoute: typeof AdminIppbBadgesRoute
  AdminIppbSettingsRoute: typeof AdminIppbSettingsRoute
  AdminJobDisputesRoute: typeof AdminJobDisputesRoute
  AdminJobEarningsRoute: typeof AdminJobEarningsRoute
  AdminJobMarketplaceRoute: typeof AdminJobMarketplaceRoute
  AdminKycRoute: typeof AdminKycRoute
  AdminLandingCmsRoute: typeof AdminLandingCmsRoute
  AdminMatrimonyRoute: typeof AdminMatrimonyRoute
  AdminNoticesRoute: typeof AdminNoticesRoute
  AdminPanSettingsRoute: typeof AdminPanSettingsRoute
  AdminPsaIdsRoute: typeof AdminPsaIdsRoute
  AdminRechargeTransactionsRoute: typeof AdminRechargeTransactionsRoute
  AdminReferralsRoute: typeof AdminReferralsRoute
  AdminServiceActivationsRoute: typeof AdminServiceActivationsRoute
  AdminServiceActivationsConfigRoute: typeof AdminServiceActivationsConfigRoute
  AdminServiceButtonsRoute: typeof AdminServiceButtonsRoute
  AdminServicePlansRoute: typeof AdminServicePlansRoute
  AdminServicesRoute: typeof AdminServicesRoute
  AdminSessionQualityRoute: typeof AdminSessionQualityRoute
  AdminTrainingEarningsRoute: typeof AdminTrainingEarningsRoute
  AdminTrainingReviewsRoute: typeof AdminTrainingReviewsRoute
  AdminTrainingSettingsRoute: typeof AdminTrainingSettingsRoute
  AdminTrainingsRoute: typeof AdminTrainingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminWalletRequestsRoute: typeof AdminWalletRequestsRoute
  AdminWalletsRoute: typeof AdminWalletsRoute
  AdminWorkBadgesRoute: typeof AdminWorkBadgesRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCertificateReissuesRoute: AdminCertificateReissuesRoute,
  AdminChatInboxRoute: AdminChatInboxRoute,
  AdminCommissionsRoute: AdminCommissionsRoute,
  AdminCreateUserRoute: AdminCreateUserRoute,
  AdminCrmLeadsRoute: AdminCrmLeadsRoute,
  AdminCrmReportsRoute: AdminCrmReportsRoute,
  AdminCscMonitorRoute: AdminCscMonitorRoute,
  AdminCscSettingsRoute: AdminCscSettingsRoute,
  AdminFinanceRoute: AdminFinanceRoute,
  AdminFormAnalyticsRoute: AdminFormAnalyticsRoute,
  AdminHoroscopeSettingsRoute: AdminHoroscopeSettingsRoute,
  AdminIppbBadgesRoute: AdminIppbBadgesRoute,
  AdminIppbSettingsRoute: AdminIppbSettingsRoute,
  AdminJobDisputesRoute: AdminJobDisputesRoute,
  AdminJobEarningsRoute: AdminJobEarningsRoute,
  AdminJobMarketplaceRoute: AdminJobMarketplaceRoute,
  AdminKycRoute: AdminKycRoute,
  AdminLandingCmsRoute: AdminLandingCmsRoute,
  AdminMatrimonyRoute: AdminMatrimonyRoute,
  AdminNoticesRoute: AdminNoticesRoute,
  AdminPanSettingsRoute: AdminPanSettingsRoute,
  AdminPsaIdsRoute: AdminPsaIdsRoute,
  AdminRechargeTransactionsRoute: AdminRechargeTransactionsRoute,
  AdminReferralsRoute: AdminReferralsRoute,
  AdminServiceActivationsRoute: AdminServiceActivationsRoute,
  AdminServiceActivationsConfigRoute: AdminServiceActivationsConfigRoute,
  AdminServiceButtonsRoute: AdminServiceButtonsRoute,
  AdminServicePlansRoute: AdminServicePlansRoute,
  AdminServicesRoute: AdminServicesRoute,
  AdminSessionQualityRoute: AdminSessionQualityRoute,
  AdminTrainingEarningsRoute: AdminTrainingEarningsRoute,
  AdminTrainingReviewsRoute: AdminTrainingReviewsRoute,
  AdminTrainingSettingsRoute: AdminTrainingSettingsRoute,
  AdminTrainingsRoute: AdminTrainingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminWalletRequestsRoute: AdminWalletRequestsRoute,
  AdminWalletsRoute: AdminWalletsRoute,
  AdminWorkBadgesRoute: AdminWorkBadgesRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface DistributorRouteChildren {
  DistributorEarningsRoute: typeof DistributorEarningsRoute
  DistributorWalletRoute: typeof DistributorWalletRoute
  DistributorIndexRoute: typeof DistributorIndexRoute
}

const DistributorRouteChildren: DistributorRouteChildren = {
  DistributorEarningsRoute: DistributorEarningsRoute,
  DistributorWalletRoute: DistributorWalletRoute,
  DistributorIndexRoute: DistributorIndexRoute,
}

const DistributorRouteWithChildren = DistributorRoute._addFileChildren(
  DistributorRouteChildren,
)

interface MatrimonyRouteChildren {
  MatrimonyProfileIdRoute: typeof MatrimonyProfileIdRoute
  MatrimonyIndexRoute: typeof MatrimonyIndexRoute
}

const MatrimonyRouteChildren: MatrimonyRouteChildren = {
  MatrimonyProfileIdRoute: MatrimonyProfileIdRoute,
  MatrimonyIndexRoute: MatrimonyIndexRoute,
}

const MatrimonyRouteWithChildren = MatrimonyRoute._addFileChildren(
  MatrimonyRouteChildren,
)

interface OperatorRouteChildren {
  OperatorIndexRoute: typeof OperatorIndexRoute
}

const OperatorRouteChildren: OperatorRouteChildren = {
  OperatorIndexRoute: OperatorIndexRoute,
}

const OperatorRouteWithChildren = OperatorRoute._addFileChildren(
  OperatorRouteChildren,
)

interface RetailerJobsRouteChildren {
  RetailerJobsJobIdRoute: typeof RetailerJobsJobIdRoute
}

const RetailerJobsRouteChildren: RetailerJobsRouteChildren = {
  RetailerJobsJobIdRoute: RetailerJobsJobIdRoute,
}

const RetailerJobsRouteWithChildren = RetailerJobsRoute._addFileChildren(
  RetailerJobsRouteChildren,
)

interface RetailerRouteChildren {
  RetailerActivateRoute: typeof RetailerActivateRoute
  RetailerCvBuilderRoute: typeof RetailerCvBuilderRoute
  RetailerEiPayRoute: typeof RetailerEiPayRoute
  RetailerFinanceRoute: typeof RetailerFinanceRoute
  RetailerFormsRoute: typeof RetailerFormsRoute
  RetailerHoroscopeRoute: typeof RetailerHoroscopeRoute
  RetailerIppbRoute: typeof RetailerIppbRoute
  RetailerJobsRoute: typeof RetailerJobsRouteWithChildren
  RetailerKycRoute: typeof RetailerKycRoute
  RetailerMatrimonyRoute: typeof RetailerMatrimonyRoute
  RetailerMoneyTransferRoute: typeof RetailerMoneyTransferRoute
  RetailerMyServicesRoute: typeof RetailerMyServicesRoute
  RetailerPageToolsRoute: typeof RetailerPageToolsRoute
  RetailerPanPortalRoute: typeof RetailerPanPortalRoute
  RetailerProfileRoute: typeof RetailerProfileRoute
  RetailerRechargeRoute: typeof RetailerRechargeRoute
  RetailerReferralsRoute: typeof RetailerReferralsRoute
  RetailerServicesRoute: typeof RetailerServicesRoute
  RetailerStaffRoute: typeof RetailerStaffRoute
  RetailerTrainingGuideRoute: typeof RetailerTrainingGuideRoute
  RetailerTrainingsRoute: typeof RetailerTrainingsRoute
  RetailerTransactionsRoute: typeof RetailerTransactionsRoute
  RetailerVirtualTrainerRoute: typeof RetailerVirtualTrainerRoute
  RetailerWalletRoute: typeof RetailerWalletRoute
  RetailerWorkRoute: typeof RetailerWorkRoute
  RetailerWorkBadgeRoute: typeof RetailerWorkBadgeRoute
  RetailerIndexRoute: typeof RetailerIndexRoute
}

const RetailerRouteChildren: RetailerRouteChildren = {
  RetailerActivateRoute: RetailerActivateRoute,
  RetailerCvBuilderRoute: RetailerCvBuilderRoute,
  RetailerEiPayRoute: RetailerEiPayRoute,
  RetailerFinanceRoute: RetailerFinanceRoute,
  RetailerFormsRoute: RetailerFormsRoute,
  RetailerHoroscopeRoute: RetailerHoroscopeRoute,
  RetailerIppbRoute: RetailerIppbRoute,
  RetailerJobsRoute: RetailerJobsRouteWithChildren,
  RetailerKycRoute: RetailerKycRoute,
  RetailerMatrimonyRoute: RetailerMatrimonyRoute,
  RetailerMoneyTransferRoute: RetailerMoneyTransferRoute,
  RetailerMyServicesRoute: RetailerMyServicesRoute,
  RetailerPageToolsRoute: RetailerPageToolsRoute,
  RetailerPanPortalRoute: RetailerPanPortalRoute,
  RetailerProfileRoute: RetailerProfileRoute,
  RetailerRechargeRoute: RetailerRechargeRoute,
  RetailerReferralsRoute: RetailerReferralsRoute,
  RetailerServicesRoute: RetailerServicesRoute,
  RetailerStaffRoute: RetailerStaffRoute,
  RetailerTrainingGuideRoute: RetailerTrainingGuideRoute,
  RetailerTrainingsRoute: RetailerTrainingsRoute,
  RetailerTransactionsRoute: RetailerTransactionsRoute,
  RetailerVirtualTrainerRoute: RetailerVirtualTrainerRoute,
  RetailerWalletRoute: RetailerWalletRoute,
  RetailerWorkRoute: RetailerWorkRoute,
  RetailerWorkBadgeRoute: RetailerWorkBadgeRoute,
  RetailerIndexRoute: RetailerIndexRoute,
}

const RetailerRouteWithChildren = RetailerRoute._addFileChildren(
  RetailerRouteChildren,
)

interface StaffRouteChildren {
  StaffDmtRoute: typeof StaffDmtRoute
  StaffFormSubmissionsRoute: typeof StaffFormSubmissionsRoute
  StaffFormsRoute: typeof StaffFormsRoute
  StaffHoroscopeRequestsRoute: typeof StaffHoroscopeRequestsRoute
  StaffIppbRoute: typeof StaffIppbRoute
  StaffLeadsRoute: typeof StaffLeadsRoute
  StaffPerformanceRoute: typeof StaffPerformanceRoute
  StaffReportsRoute: typeof StaffReportsRoute
  StaffServicesRoute: typeof StaffServicesRoute
  StaffIndexRoute: typeof StaffIndexRoute
}

const StaffRouteChildren: StaffRouteChildren = {
  StaffDmtRoute: StaffDmtRoute,
  StaffFormSubmissionsRoute: StaffFormSubmissionsRoute,
  StaffFormsRoute: StaffFormsRoute,
  StaffHoroscopeRequestsRoute: StaffHoroscopeRequestsRoute,
  StaffIppbRoute: StaffIppbRoute,
  StaffLeadsRoute: StaffLeadsRoute,
  StaffPerformanceRoute: StaffPerformanceRoute,
  StaffReportsRoute: StaffReportsRoute,
  StaffServicesRoute: StaffServicesRoute,
  StaffIndexRoute: StaffIndexRoute,
}

const StaffRouteWithChildren = StaffRoute._addFileChildren(StaffRouteChildren)

interface TrainerRouteChildren {
  TrainerTrainingsRoute: typeof TrainerTrainingsRoute
  TrainerWalletRoute: typeof TrainerWalletRoute
  TrainerIndexRoute: typeof TrainerIndexRoute
}

const TrainerRouteChildren: TrainerRouteChildren = {
  TrainerTrainingsRoute: TrainerTrainingsRoute,
  TrainerWalletRoute: TrainerWalletRoute,
  TrainerIndexRoute: TrainerIndexRoute,
}

const TrainerRouteWithChildren =
  TrainerRoute._addFileChildren(TrainerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  BookletRoute: BookletRoute,
  DistributorRoute: DistributorRouteWithChildren,
  InstallRoute: InstallRoute,
  LoginRoute: LoginRoute,
  MatrimonyRoute: MatrimonyRouteWithChildren,
  NsdlCallbackRoute: NsdlCallbackRoute,
  OperatorRoute: OperatorRouteWithChildren,
  RegisterRoute: RegisterRoute,
  RetailerRoute: RetailerRouteWithChildren,
  StaffRoute: StaffRouteWithChildren,
  TrainerRoute: TrainerRouteWithChildren,
  WelcomeRoute: WelcomeRoute,
  WorkerWorkerIdRoute: WorkerWorkerIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
